### ISSUE TITLE
Request: Inspect element

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#100]
Tweaking and refining email designs, I use Chrome's inspect element tool to quickly modify css and live edit a specific element. I am aware that MJML preview updates immediately but it's a hassle to dig through code to find specific CSS affecting a particular element.

Having an inspector panel or some sort would be awesome functionality that would save a ton of time!

**Comment by meriadec** [comment]
Developper tools are now available in packaged mode.

![inspect](https://cloud.githubusercontent.com/assets/315259/25279225/15aca128-26a6-11e7-843a-00695a3acf50.gif)

I will close the issue on the 2.0.0 release.

**Comment by dshastry** [comment]
👍
