### ISSUE TITLE
Beta builds fail on windows with webpack errors in react-icons

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml-app#101]
I took the latest source, ran `npm install` and then `npm run dev`
Webpack fails to compile with lots of errors:

```
ERROR in ./~/react-icons/md/star.js                    
Module parse failed: C:\Users\reith\Downloads\mjml-app-2.0.0-beta3\node_modules\react-icons\md\star.js Unexpected token (6:4)
You may need an appropriate loader to handle this file type.                                                                                                               
SyntaxError: Unexpected token (6:4)
```      
...and so on for the other js files in ./~/react-icons/      

npm run package also wont produce usable builds
Did the build process change with the new electron boilerplate?

**Comment by meriadec** [comment]
Hello @janus-reith , yes the build changed, I re-updated the core, from https://github.com/chentsulin/electron-react-boilerplate some weeks ago, but I haven't tested on windows. I will test that on friday (maybe just some tweaks on the webpack config will do the trick! I hope..)

**Comment by meriadec** [comment]
That did the trick 🎉 
So I uploaded the windows package for beta3.

Tell me if it worked for you!
