### ISSUE TITLE
Request: Grouped Projects & Project Search

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#102]
We use MJML to create numerous types of email newsletters, etc. It would be nice to have a feature where we could group mail templates together into a folder to be able to organize by campaign. Once there's about 25-30 emails that have similar look and feel (aka thumbnails are similar), it becomes time consuming to read the little project name. Folders would help greatly!

Also a search field that searches for either folder group name or email name would be awesome and speed things up a lot, especially when templates are shared across a larger team!

Quick mockup of requested feature attached :
![image](https://cloud.githubusercontent.com/assets/4194561/25285140/d9932184-267e-11e7-951d-baa3f11dc757.png)

**Comment by meriadec** [comment]
Re, @dshastry !

Yes, a way to group templates is definitely something useful, but it can also be a complete fail if badly done. So, let's keep the discussion open, and precise the way folders/groups/tags can be created.

Do you know some web-app/software that use a similar behaviour, that we can inspire of?

**Comment by dshastry** [comment]
Agreed. I think keeping it super simple would be the key in ensuring the feature's success. I think a tag feature would complicate things for an initial release. Limiting to simple folder groups that can only be 1 level deep should work from a UX standpoint. I guess some good functional examples of how the behavior can work are below:

1. Best Example: Apple iOS drag and drop apps. All templates exist outside of folders by default but create folders when dragged on top of existing template (http://1.bp.blogspot.com/-UN9GVn12v-k/VOH3UHm4fdI/AAAAAAAAAIY/zoARxngzHuI/s1600/Hide-Applications-iOS-8.gif)
2. https://dribbble.com/shots/2041325-Asset-Library-Drag-Drop

**Comment by ngarnier** [comment]
I love the UX of iOS apps but I do think tags/labels are more appropriate for email. Off the top of my head, here are a few reasons why:

- You might want to gather a template in different groups, example: `Marketing` and `Black Friday 2017 Campaign`, which folders don't enable but labels do.
- Tags/Labels enable powerful cross search/filtering features (even if not available at first, that's a great potential addition).
- Labels enable you to see all of your templates with the category they're associated to at a glance, without having to actually click and browse inside a folder to see if the template you're looking for is there. If it's becoming too much and you don't want to see them all, just filter specific ones out.

**Comment by dshastry** [comment]
totally agree @ngarnier. I mentioned folders only to begin with to keep things simple yet offer a basic sorting functionality for a near term beta release. Progressive enhancement to add labels/tags in later releases is totally the way to go though.

As @meriadec mentioned previous, I think tagging/labelling adds a few complexities from a ux standpoint initially, because it can get confusing if not done right. I'll keep on the lookout for examples where this is done nicely and keep posting back here.

I do like your point about being able to filter based on tags/labels; it would make the desktop app so much more powerful especially for larger teams using shared templates. I feel like building and refining that search piece can be a whole feature request in and of it self..lol!

**Comment by ddeath** [comment]
It would be great to have ability to create folders. For me it is this use case:

I work on multiple projects, so I have mixed emails from company A and company B together. Simple one level deep folder structure would solve this case.

The labeling would be overkill because I do not have problem find the email by it name as far as there are not same names (because WelcomeEmail has company A and company B also...). Simple search in folder would do it for me.

**Comment by MateuszDabrowski** [comment]
+1 but i actually think folders structure already works in app (you just have to create it in finder/explorer)

**Comment by ddeath** [comment]
@MateuszDabrowski yop you are right. Did not know about that feature :) thanks for pointing out

**Comment by meriadec** [comment]
closing in favor of https://github.com/mjmlio/mjml-app/issues/220

**Comment by prashantdwivedi** [comment]
### **Custom mjml cover image** - [here](https://github.com/prashantdwivedi/custom-mjml-cover-image)
![https://i.imgur.com/hQnb2tv.png](https://i.imgur.com/hQnb2tv.png)
