### ISSUE TITLE
Highlight Tag & Contents

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#116]
Great feature I noticed in Brackets recently that I think could work great in MJML is tag highlighting. I know we currently have a tag open/collapse function, but sometimes I have a tag open and I'm editing contents, and it would be nice to see where the tag ends. Especially useful when nesting multiple divs

![image](https://cloud.githubusercontent.com/assets/4194561/25536682/483e49d8-2c01-11e7-9b00-92fc38fed28c.png)

**Comment by meriadec** [comment]
Yep, seems to be trivial to implement with CodeMirror's Tag Matcher https://codemirror.net/demo/matchtags.html

**Comment by dshastry** [comment]
Awesome! Yeah I find myself hunting when I have multiple divs open, and it's annoying to sometimes toggle elements expand/closed to see where the closing tag is, so it would certainly be a great help!

**Comment by ngarnier** [comment]
@meriadec all it takes is adding this snippet [here](https://github.com/mjmlio/mjml-app/blob/develop/app/components/FileEditor/index.js#L148)
```js
      matchTags: {bothTags: true},
      extraKeys: {"Ctrl-J": "toMatchingTag"} // optional - to enable keyboard shortcut to jump from an opening tag to its matching tag
```

**Comment by meriadec** [comment]
Worked well, with the highlight addon, but as it overrides the whole line text color (no more coloration) it can be annoying, so I will make it optional via configuration.

![screenshot-1494577835_345x252](https://cloud.githubusercontent.com/assets/315259/25989920/2a116596-36fe-11e7-986b-4dfc2e1d68f1.png)

**Comment by dshastry** [comment]
Works amazing and I love the new functionality! Thanks guys.

Any possibility to extend this to include CSS highlighting in addition to MJML? Would be helpful when writing/examining/editing css in the mj-head section
