### ISSUE TITLE
Preserve Tag Collapse Order

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#117]
Small detail but similar to Photoshop's folders, it would be nice if the app could preserve the collapsed/open state for tags between project saves/opens.

When handing off files between multiple designers the first image works a lot better than the second from a legibility/cleanliness standpoint. I know individuals can go in and collapse everything themselves too, but if the app could preserve this behaviour by default it would save time.

![image](https://cloud.githubusercontent.com/assets/4194561/25536831/c514bd5c-2c01-11e7-9d9f-4a3f62e78c05.png)

![image](https://cloud.githubusercontent.com/assets/4194561/25536846/d2e1f9ae-2c01-11e7-8f9d-b9f98e69f4a9.png)

**Comment by meriadec** [comment]
Hey good idea but hard to implement as you describe. Because it would need to store each folded line, and keep track of them as you type / fold.

A compromise can be defining a "default folding level", with will fold the tags that are superior to a certain level of nesting. What do you think?

**Comment by dshastry** [comment]
I like that @meriadec! Maybe collapse all tags to the <mj-section> level on open and then users can expand as per their need?

Since that's the most basic building "block" if you will, it seems logical. Thoughts?

**Comment by meriadec** [comment]
In next release (2.2.0) you will be able to choose to auto-fold lines based on indentation:

![screenshot-1493991746_320x80](https://cloud.githubusercontent.com/assets/315259/25747914/7b11c990-31a9-11e7-9aac-403b8dec713e.png)

Here is the result with a fold level of `3`:

![screenshot-1493991757_540x397](https://cloud.githubusercontent.com/assets/315259/25747913/7af4fefa-31a9-11e7-8197-5f1d9cd01ead.png)

**Comment by dshastry** [comment]
Just downloaded the latest release to try this out and I think it works great! However, I did notice that it only collapses tags within <mj-body> and not in <mj-head>.

Here's how it looks on open : 
![image](https://cloud.githubusercontent.com/assets/4194561/26004120/5b370436-36fa-11e7-8045-06a5a7510300.png)

Could we extend the collapse functionality into mj-head as well?

**Comment by meriadec** [comment]
strange.. can you try indenting your `mj-head` at the same level as `mj-body`, then re-open the project?

**Comment by dshastry** [comment]
that did it! weird why it doesn't collapse if not indented?

**Comment by meriadec** [comment]
Yes, it's because it doesn't really do an XML parsing (I think it will be costly in term of performance), but use indentation. You can try the beautify tool to not worry about indentation !

**Comment by dshastry** [comment]
Gotcha. Makes sense. I'll try that out. Thanks!
