### ISSUE TITLE
Open Button Does Not Work

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#118]
![image](https://cloud.githubusercontent.com/assets/4194561/25538064/cc344f8a-2c06-11e7-9886-2efe42b919ca.png)

Clicking the open button in release 2.0.1 does nothing. No action observed

**Comment by meriadec** [comment]
The open button open the folder in the file browser. If you are on Mac, there is a chance that the Finder windows is *behind* the MJML App windows.. :) see #106

Should be fixed in 2.1.0
