### ISSUE TITLE
Take only .mjml files

### ISSUE THREAD

**Issue by Apercu** [mjmlio/mjml-app#12]
The open feature should only accept files with the `.mjml` extension, to prevent user missclicks and other things.

**Comment by GuillaumeBadi** [comment]
I guess: https://github.com/atom/electron/blob/master/docs/api/dialog.md#dialogshowopendialogbrowserwindow-options-callback

**Comment by Apercu** [comment]
Yes ;) On it

**Comment by GuillaumeBadi** [comment]
Faster than a bullet
