### ISSUE TITLE
Feature Request: Export to JPEG/Image

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#120]
Would be great to be able to export email design as an image. I sometimes want to design and print out/share emails for offline use etc and it's challenging to do this with an HTML file. Currently I post the file online and use a thirdparty HTML to JPEG converter to give me an image.

If this was part of the export options it would be fantastic!

**Comment by meriadec** [comment]
Good idea. I think it's not hard to implement with electron's `capturePage`

https://github.com/electron/electron/blob/master/docs/api/browser-window.md#wincapturepagerect-callback

**Comment by meriadec** [comment]
Done in 2.2.0, thanks to @ngarnier

**Comment by dshastry** [comment]
Getting scrollbars on export. Can we do something to prevent that?


![index-desktop](https://cloud.githubusercontent.com/assets/4194561/26468418/fa6d427a-415b-11e7-9b2f-f037b923b754.png)
![index-mobile](https://cloud.githubusercontent.com/assets/4194561/26468419/fa6fd648-415b-11e7-9145-40c29455f4ce.png)

**Comment by dshastry** [comment]
quick bump, @meriadec. Sorry to bring up this minor issue again but I'd love if you or the team could take a look at this. Surprisingly this is now a functionality we've been using a lot in our email design workflow and I'm having to crop out the scrollbars in photoshop.

**Comment by meriadec** [comment]
Hey @dshastry , yes I forgotten this one because it was closed :D
So I reopen it, I could work on it on Friday I think. 

Keep updated!
