### ISSUE TITLE
Projects don’t work in Dropbox subfolders

### ISSUE THREAD

**Issue by jonathanhandt** [mjmlio/mjml-app#121]
Hey guys,

love your app! Really powerful and perfect for prototyping realistic email design systems!

With 2.x.x version of the mac app I currently experiencing one problem which is sort of a file-system bug: After creating a new project (single or header & footer) in a dropbox subfolder the editor and file list on the left seem to be deactivated. In addition to this, I can't open older projects created with atom.

<img width="864" alt="screenshot 2017-05-03 10 54 47" src="https://cloud.githubusercontent.com/assets/28342419/25653841/f4b70fe2-2fee-11e7-9992-78e6fe8edac0.png">

**Comment by meriadec** [comment]
Heyo @jonathanhandt , thanks for reporting.
As you said, seems like an issue with file system, maybe because DropBox is synchronizing things at the same time.. dunno. I have to test if I can reproduce.

Keep updated

**Comment by dshastry** [comment]
@meriadec , Same issue noticed with Google Drive folders on the latest release. Previous releases haven't had an issue picking up older projects.

**Comment by meriadec** [comment]
Hey there, I tried with DropBox (on Linux) and didn't notice any problem. Do you still have it?

If yes, can you open developper tools (View -> Toggle developper tools) , go to "Console" tab, then paste eventual error?

**Comment by dshastry** [comment]
It's weird I installed the last release (a week ago) and the issue has now disappeared. I did have this problem on previous releases though. Not sure what changed; also, I'm on Mac OSX Sierra.

**Comment by meriadec** [comment]
Ok :) Maybe problem occured at the exact same time that dropbox was doing a sync, or something.
I close for the moment, feel free to re-open at anytime if pb occurs again!
