### ISSUE TITLE
Feature Request: Recently Sent Emails/Address Book

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#125]
As you guys are probably aware by the numerous number of requests I keep pushing up here, I use MJML app a lot in my day to day! One aspect that gets a little tedious each time I send emails to my team is having to input every single time different emails for the various team members I'd like to send to.

I'd love if there was a way to incorporate either an address book functionality (eg: integration with system address books or self contained address book within Mailjet) or to show the most recently emailed contacts. That way I don't have to type out the email addresses each time for each of my team members. Makes the workflow a little bit easier when collaborating

**Comment by meriadec** [comment]
Hey @dshastry , your suggestions are welcome, and precious because they come from a *real world* usage. So don't limit yourself :smile: 

Interesting suggestion, do you see them like, for example the 5 last emails used, displayed as "tags" below the email input? Or a more "complex" contact handling, with ability to add/remove them etc (seems more complicated).

**Comment by dshastry** [comment]
Honestly, I think both @meriadec. The first as a near term faster solution but the second as a longer term higher value add feature. Last 5 would be great for now, and I think a tag could be a good way to implement it. A better way may be to do it inline if we're thinking of adding in the multiple targets since it can get messy to have tags below each field if there are multiple. For example you can start typing and you get a dropdown. Something like [this](https://cdn.dribbble.com/users/1641/screenshots/2979871/-dribbble.jpg) would probably be ideal.

In the future a more complex contact handling would be more valuable to users because that way they don't have to remember full email addresses and can find targets by name. I think the simplest way if possible would be integrating with the system address book. Just read data from it. Not sure if this can be done currently or how feasible it is. That way MJML app doesn't have to manage the contacts, only display data from them. There's also no user expectation or frustration of two separate disparate address books with out of sync info. Since the system address books usually will sync with Google Apps/Exchange/iCloud/etc in realtime the latest contact info will always be pulled in.
