### ISSUE TITLE
Feature Request: Multiple Target Emails

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#126]
Building off of #125 would be great if we were able to define multiple target emails. Currently, it's a lot of clicks if I want to send one message out to my 5 team members for review. Would be much simpler if we can add  additional number of target email recipients, with maybe a little "+" button to insert a new one.

**Comment by meriadec** [comment]
That's a good idea. Leads to other possible features, for example ability to send to a list located in a CSV file, for example? :mailbox: 

But yep, for a start, having multiple targets (with a limit, e.g 30 people max) sounds good.

**Comment by dshastry** [comment]
Read my mind! Haha 😉 

CSV down the road would be fantastic but yes a limited list currently would be a great addon
