### ISSUE TITLE
Older projects don't open in latest update

### ISSUE THREAD

**Issue by Miriam253091** [mjmlio/mjml-app#128]
Hello. I like your app, but since updating to the latest version I can't open the projects generated by older versions. Also the open button in the right corner doesn't work.

![captura de pantalla 2017-05-12 a las 2 29 55 p m](https://cloud.githubusercontent.com/assets/24721894/26013961/2e9acfd6-3720-11e7-9ba1-f04c184830e4.png)

**Comment by meriadec** [comment]
Hello @Miriam253091, the way templates are stored in the v1 is not compatible with v2.
For the moment, what you can do is manually save your old templates to `.mjml` files, then open them in the new app.

n.b: you can re-download the MJML App v1 here: https://github.com/mjmlio/mjml-app/releases/tag/1.8.1

I close the issue as it is not really a _bug_ , but feel free to ask if you need more help!
Happy coding.
