### ISSUE TITLE
Updating the app doesn't work

### ISSUE THREAD

**Issue by silvenon** [mjmlio/mjml-app#129]
When I click this button, nothing seems to happen:

![screen shot 2017-05-12 at 23 30 29](https://cloud.githubusercontent.com/assets/471278/26017653/020c52fa-376b-11e7-8d0a-878f643feaa4.png)

No error in the console either.

**Comment by meriadec** [comment]
Hey @silvenon, thanks for reporting, I need to investigate.

You can download the new version manually here: https://github.com/mjmlio/mjml-app/releases/tag/2.2.0

**Comment by nvassos** [comment]
Downloading the app seems to break the app 

https://www.dropbox.com/s/0fu1yn981db7z1j/Screenshot%202017-05-15%2011.05.53.png?dl=0

Any idea why this is happening?
