### ISSUE TITLE
Old Projects cannot be opened with new update

### ISSUE THREAD

**Issue by nvassos** [mjmlio/mjml-app#130]
Why the old projects I had don't work after updating to 2.2.0?

**Comment by noahmanion** [comment]
Having this problem as well. There is a folder in my root direcory called mjml-app that contains a folder called mjml-projects, which itself contains a bunch of .json files that seem to be my old projects, however I can't seem to open any of them.

**Comment by icarobregon** [comment]
Same problem...

**Comment by nvassos** [comment]
I have over 150 emails created, need an answer or downgrading version link. Thanks.

**Comment by icarobregon** [comment]
Hi @nvassos,

Seems a problem with version 2. I have tried all of them and it has not worked for me.

You can find previous versions to downgrade here: https://github.com/mjmlio/mjml-app/releases

**Comment by nvassos** [comment]
The funny thing is the version I had was v2 but the first. I downloaded older versions and still doesn't work. I need someone from the dev team to respond as this is unacceptable.

**Comment by noahmanion** [comment]
Whoa. Slow down. Not responding to a support request 6 hours after it posted is not unacceptable. However, in my opinion, demanding immediate response on free & open source software is. I visited the release page posted above, downloaded 1.8.0, opened it and my templates were all still available (I'm on OSX 10.12.4). Your templates very likely still exist on your machine, but are inaccessible using the latest release.

**Comment by nvassos** [comment]
Not, what's not unacceptable is releasing a version that doesn't load older files files. It can be answered in 20 hours if needed to. 

And I did download 1.8 and did not load the files.

**Comment by meriadec** [comment]
Hello @nvassos, I understand your frustration but as explained in https://github.com/mjmlio/mjml-app/issues/128 and https://github.com/mjmlio/mjml-app/issues/119, the storage format of v1 and v2 are not compatible.

This project follow [semantic versionning](http://semver.org/), so using v2 over v1 _semantically means_ that there will be incompatibilities. That's the way many open source project works so, sorry but nope, there is nothing "unacceptable". (Did I mention this app is free?)

After that said, you have ~150 emails created in v1 so I understand that copy-pasting every single template manually is not an option. I would advise you to write a script that will convert all JSON files in `~/mjml-app` into folders containing corresponding `.mjml` files.

Don't hesitate to ping me on the [MJML Slack](https://slacking-inviter.herokuapp.com/) if you need any help!

**Comment by nvassos** [comment]
I have no issue copy pasting. Will copy pasting work?

**Comment by meriadec** [comment]
Yeah, sure. Two solutions to "extract" templates: 

- Open the app v1 ([last release here](https://github.com/mjmlio/mjml-app/releases/tag/1.8.1)) and copy-paste each template MJML content in a separate `.mjml` file

or

- If you have issues with the app v1, you can directly extract data from `~/mjml-app` folder:
  Files are JSON in the format:

  ```
  {
    "id": "abc01",
    "name": "template name",
    "mjml": "<mjml> .... ... ... </mjml>",
  
    ...etc
  }
  ```
  So here, you take only the `mjml` value, then paste it into a `.mjml` file.

Best way to work with the v2 is having *one* folder by template, and a `index.mjml` file in the folder (it's used for the thumbnail).

After that, you can open any folder with the "Open project" button in MJML App v2.

**Comment by nvassos** [comment]
I did try running 1.8.1 version but all I get is a black screen without any options, not even in menu. 

https://www.dropbox.com/s/usuqhjp9dws560u/Screenshot%202017-05-16%2009.14.39.png?dl=0

**Comment by ngarnier** [comment]
@nvassos following a discussion on the [MJML slack](https://slack.mjml.io/), it seems this bug is happening when opening a file with invalid MJML code. 

Try this to fix it: 
- identify the file with invalid MJML code
- fix the mistakes (using a text editor like TextEdit, Atom or any other text editor)
- try opening the app again
