### ISSUE TITLE
Add a Hide Command

### ISSUE THREAD

**Issue by jbickelhaupt** [mjmlio/mjml-app#131]
Would LOVE the ability to have a Hide command (with keyboard shortcut) available in the app menu. I switch between apps or app/desktop often enough that minimizing the app window to move somewhere else becomes pretty burdensome. It would be a HUGE boost to my efficiency.

I actually tried to manually add a shortcut for this myself within the OS X settings on my Mac, but it wouldn't let me make any shortcuts for the MJML app.

**Comment by meriadec** [comment]
Hey @jbickelhaupt , good idea. Can you make a PR based on develop branch?

You should find an example of what to do here: https://github.com/chentsulin/electron-react-boilerplate/blob/master/app/menu.js#L54-L55

The file you want to modify is here: https://github.com/mjmlio/mjml-app/blob/develop/app/main.development.js#L130

**Comment by meriadec** [comment]
done here https://github.com/mjmlio/mjml-app/pull/132
