### ISSUE TITLE
Figure out how to serve local images

### ISSUE THREAD

**Issue by meriadec** [mjmlio/mjml-app#134]

**Comment by meriadec** [comment]
example using local images:

![screenshot-1495193399_1319x696](https://cloud.githubusercontent.com/assets/315259/26246112/b2d4269a-3c97-11e7-84eb-69b86f0b7ff1.png)

**Comment by dshastry** [comment]
Building on this, it would be nice if an upload/import functionality was supported. That way the tool can be opened up a bit more to users who don't necessarily code but want to make simple edits. Kinda like a WSIWYG

**Comment by meriadec** [comment]
I'm not sure I understand it well. What you are suggesting is a way to upload an image to a distant server / image service?

**Comment by dshastry** [comment]
Well, yes and no. It would work in both instances. In the event that I write MJML code and hand it off to a non-technical person that wants to make simple edits such as swapping a header image for example, a click to upload would be great. Also sometimes files are all over the filesystem and so links will break when the email is exported. If on import an assets folder was created and images were copied over that would help greatly when handing over an email template for implementation to developers or to marketing.

**Comment by meriadec** [comment]
OK, I think I understand the request.
But pretty hard to implement, because it means changing something _on the right side (preview side)_, and make the _left side_ updating according to modification.

Finding the source MJML line that impact a particular `<img>` tag in HTML will be tricky by design. Solution used by MJML WISIWYG is to build an intermediary HTML abstraction, which can easily find relations between MJML tags and DOM nodes.

Maybe in a distant future of the app :smile:

**Comment by dshastry** [comment]
Haha sounds good! Your second paragraph went totally over my head! (Hint: that's why I'm a designer and not a dev lol!)

**Comment by divyeshmakwana96** [comment]
@dshastry I created a cli utility which can do just that. You can choose your hosting provider and build HTML output. It'll take care of the hosting and swapping images for you. There is a test email functionality as well. https://github.com/divyeshmakwana96/Pochta
