### ISSUE TITLE
No obvious was to save a project in 2.20

### ISSUE THREAD

**Issue by spidercrab** [mjmlio/mjml-app#138]
Can't find a way to save a project which should be easy to fin

**Comment by meriadec** [comment]
Hey @spidercrab , what do you mean by saving a project?
All changes are saved to disk as you write in the editor.
You can open the project folder by using the "Open" button.

**Comment by spidercrab** [comment]
Hi,

In that case i didn't realise there was an auto save.  However, i tried to open a file I was working on but the MJML code is not visible yet the rendered code is visible.  I can't find any way to get at the code.

I will try to pin point this further and let you know.

Hey, keep up the great work.

Gary Naylor

Sent with Airmail


On 24 May 2017 at 20:59:41, Meriadec Pillet (notifications@github.com) wrote:

Hey @spidercrab , what do you mean by saving a project?
All changes are saved to disk as you write in the editor.
You can open the project folder by using the "Open" button.

**Comment by meriadec** [comment]
Ok no problem! :)

Yes, the app is "folder based" so maybe it's not very clear on how to open only a single file.
Hope it'll fit your needs with it! Happy coding.

I close this for tracking purpose. Feel free to re-open if any question.
