### ISSUE TITLE
show version of mjml used, in a "help" or "about" or "whatever" page

### ISSUE THREAD

**Issue by meriadec** [mjmlio/mjml-app#14]
could be useful for debugging purposes

**Comment by Apercu** [comment]
What about in a bottom corner?

**Comment by meriadec** [comment]
not bad, but it will not fit very well in editor mode:

![screen shot 2016-03-14 at 13 52 28](https://cloud.githubusercontent.com/assets/315259/13745028/0d468a6e-e9ec-11e5-8241-87ed55c2af36.png)

i don't know where we can put it. any thought @GuillaumeBadi ?

**Comment by Apercu** [comment]
So next to the title I think
