### ISSUE TITLE
mj-class or css-class attributes not working

### ISSUE THREAD

**Issue by derekoakley** [mjmlio/mjml-app#141]
I can't seem to get either mj-class or css-class attributes to work on tags `<mj-section>` or `<mj-text>` in release 2.3.0. Any ideas?

**Comment by meriadec** [comment]
Hi @derekoakley , that's weird!
Can you paste a code example of the problem?

**Comment by MateuszDabrowski** [comment]
Css-class is not yet availble in 2.3.0 version of app (despite being suggested by the app) - it needs newer version of MJML that is still in beta available in NPM.

**Comment by meriadec** [comment]
@MateuszDabrowski what do you mean by "despite being suggested by the app"?

The app will always be shipped with the latest stable MJML release.
BTW, you can use a locally installed MJML version, by using the "custom MJML engine setting":

![mjml](https://cloud.githubusercontent.com/assets/315259/26622365/7357c790-45ea-11e7-9ef8-15973d343c50.png)

**Comment by derekoakley** [comment]
Ok thank you @meriadec, shouldn't mj-class attribute work tho?

Also re: css-class, I thought as much but the current [mjml documentation](https://mjml.io/documentation/) mentions only css-class.

**Comment by MateuszDabrowski** [comment]
@derekoakley It would be best if you could paste your code. <mj-class> works fine for me so it may (or may not) be your code.

@meriadec Sometimes while writing code app suggest adding css-class (for example when you write "<mj-table cs".

**Comment by meriadec** [comment]
Oh yes, good point @MateuszDabrowski  :) It should not have been added to autocomplete.

**Comment by aybhalala** [comment]
I defined a color class as follows: 
<mj-attributes>
  <mj-class name="main-section" color="#fff" />
</mj-attributes>

But when I call this in section or wrapper it does not work. 
<mj-wrapper css-class="main-section">
or
<mj-section css-class="main-section">

**Comment by ngarnier** [comment]
@aybhalala there is no code visible in your comment. 

Also please open an issue on the [mjml repo](https://github.com/mjmlio/mjml), this issue was closed and is for the mjml app only.
