### ISSUE TITLE
Feature Request: Drag and Drop File Open

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#143]
Currently unable to open an MJML project if I drag and drop the index.mjml file onto the MJML app. All I get is this : 
![image](https://cloud.githubusercontent.com/assets/4194561/26740020/975c9d0e-4799-11e7-98f2-a6eb7d488a01.png)

Would be fantastic and make things a lot easier if the file/project could be opened if an MJML file is dragged onto the application.

**Comment by meriadec** [comment]
Interesting feature. Should be do-able pretty easily using drop-event.
https://discuss.atom.io/t/possible-to-get-local-filesystem-path-from-drag-and-drop-file/28858

**Comment by meriadec** [comment]
![drop](https://user-images.githubusercontent.com/315259/27220373-359a2090-5285-11e7-879c-8e239ecf6b4b.gif)

**Comment by dshastry** [comment]
Awesome!

**Comment by meriadec** [comment]
:) thx! I prefer to keep issue open until released on master.
In fact, github automatically closes issues when merged in default branch, and have a commit message with the issue tag!

**Comment by dshastry** [comment]
Ah gotcha. Apologies for closing it out. Looks great, excited for the new feature

**Comment by meriadec** [comment]
I think you were right. Better to close it, and I will use github milestones to track next release progress.
