### ISSUE TITLE
Documentation in MJML/Menu doesn't work

### ISSUE THREAD

**Issue by MateuszDabrowski** [mjmlio/mjml-app#146]
In Mac MJML App 2.3.0, in MJML the Documentation link stopped working (clicking does nothing).

**Comment by meriadec** [comment]
thanks for reporting, reproduced on osx too.

**Comment by MateuszDabrowski** [comment]
Problem persist on 2.4.0 for Documentation, Browser Editor and Download Button.

Seems like all external links doesn't work on osx

**Comment by meriadec** [comment]
Arf.. forgot that one for 2.4.0 😞 I develop on Linux so don't have the problem.
Let's try with `openExternal` which [seems to be more adapted for urls](https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options-callback).
