### ISSUE TITLE
Try-it-live link in App

### ISSUE THREAD

**Issue by MateuszDabrowski** [mjmlio/mjml-app#147]
In MJML App there is link to Documentation. It would be nice to have a link to Try-it-live (a dream would be to automatically open try-it-live with the content of current project, but just simple link to try-it-live would be a nice think too)

**Comment by meriadec** [comment]
Good idea. Can you make a PR for this (based on develop branch)?

the file to modify is here: https://github.com/mjmlio/mjml-app/blob/develop/app/menu.js#L24-L29

**Comment by meriadec** [comment]
Absolutely. Thanks @MateuszDabrowski :)
