### ISSUE TITLE
Images on MJML App Github.io Site

### ISSUE THREAD

**Issue by MateuszDabrowski** [mjmlio/mjml-app#149]
Some of them are not up to date (like the sender API window in the bottom), some are not loading at all (checked on Firefox and Safari with ublock on and off):

![zrzut ekranu 2017-06-07 o 17 36 53](https://user-images.githubusercontent.com/13339456/26887322-03d651ca-4ba8-11e7-8852-944feb27a6de.png)

**Comment by meriadec** [comment]
Good catch
