### ISSUE TITLE
support to win platform

### ISSUE THREAD

**Issue by rcorzogutierrez** [mjmlio/mjml-app#15]
It works for me perfectly on windows platform!!!!!!!

share binaries

https://drive.google.com/file/d/0B8-xnAhV5qLBdThEMVhKZ2xCdk0/view?usp=sharing

**Comment by meriadec** [comment]
hey! Thanks a lot for this, we had some issues with generating it on windows.
I just added it to [the releases page](https://github.com/mjmlio/mjml-app/releases/tag/1.1.0) and will update the site soon!

**Comment by GuillaumeBadi** [comment]
Awesome! Did you have to adjust anything in the `build.js` file ? You might want to commit it if so ;)

Thanks for the contribution! :+1:

**Comment by rcorzogutierrez** [comment]
a pleasure!!!! Thank you for this great project
