### ISSUE TITLE
MJML Emmet

### ISSUE THREAD

**Issue by MateuszDabrowski** [mjmlio/mjml-app#151]
It would be absolutely awesome to create something Emmet style for MJML App.

For example: 
`mjs[bg-color="ffffff"]>(mjc[width="50%" bg-color="007ac3"]>mjt>p{Lorem15})*2^mjs[bg-color="007ac3"]>mjb{Submit}`
Would create:
 ```
<mj-section background-color="#ffffff">
        <mj-column width="50%" background-color="#007ac3">
          <mj-text>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent hendrerit erat ipsum, vel ultrices nulla.</mj-text>
        </mj-column>
        <mj-column width="50%" background-color="#007ac3">
          <mj-text>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent hendrerit erat ipsum, vel ultrices nulla.</mj-text>
        </mj-column>
      </mj-section>
      <mj-section background-color="#007ac3">
      <mj-column>
<mj-button>
  Submit
        </mj-button>
        </mj-column>
      </mj-section>
```

**Comment by meriadec** [comment]
Feature can be cool, although not really the right place to do that. For me, correct way is to write a custom codemirror plugin (like https://github.com/emmetio/codemirror), then make MJML App use the plugin.

**Comment by MateuszDabrowski** [comment]
Ok.

By the way, is it possible to PR changes to syntax suggestions in app?

**Comment by meriadec** [comment]
yep sure! if you spot any problem, the file is located here: https://github.com/mjmlio/mjml-app/blob/develop/app/helpers/codemirror-autocomplete-mjml.js
