### ISSUE TITLE
Accusing illegal attributes on social component

### ISSUE THREAD

**Issue by lucasnantonio** [mjmlio/mjml-app#153]
Hi, i've created custom attributes for my social networks, and the web linter keeps saying they're illegal, even though they work perfectly.

![image](https://user-images.githubusercontent.com/13240286/27083368-b2afd5de-501e-11e7-8f85-56cb84e3c1e9.png)

**Comment by meriadec** [comment]
Hey @lucasnantonio , as you say those are false positive. It's because the mjml-validator is based on the default attributes of the component, and does not take in account any new attribute.

You can safely ignore this error, maybe this can be improved in the future.
What do you think, @iRyusa ?

**Comment by iRyusa** [comment]
Hi @lucasnantonio 

Yes new `mj-social` will fix that, because of the new way you'll declare the social element inside an `mj-social` in MJML4

**Comment by tristolliday** [comment]
Hi there, I am getting the same issue with v2.8.0 , but when rendering as html, it just ignores the tag and it doesn't end up in the final .html file

**Comment by meriadec** [comment]
Hello, the difference is that app < 2.8.0 and the try-it-live uses mjml 3.*
The 2.8.0 app uses mjml 4.

**Comment by tristolliday** [comment]
Thanks, @meriadec that makes sense. Is there a link to the MJML4 docs?
Cheers, Tris

**Comment by meriadec** [comment]
The online doc for MJML 4 is not finalized/live yet, but you can read doc for each package in the mjml repository.

Example for mj-social: https://github.com/mjmlio/mjml/tree/master/packages/mjml-social
