### ISSUE TITLE
Feature Request : Mass Export Emails

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#154]
One of the features I wish I had as I'm working on multiple templates is a mass export feature. For example I have a header.mjml file that's used as a common element across 12 email templates. Each time I make a change in header.mjml, I'm having to open each individual email template and export the HTML out. It would be very very helpful if we are able to multi-select email templates and mass export the HTML for all of them. Would save a ton of time!

**Comment by meriadec** [comment]
Interesting idea, just to understand better , is it exporting multiple emails _of the same project_, or exporting multiple projects at the same time?

**Comment by meriadec** [comment]
Also, maybe the value of the "Project" was a wrong direction, for the app. I feel like it's not so used

**Comment by dshastry** [comment]
Essentially its multiple projects. I agree maybe project isn't the best term. so for example, my current workflow is that each set of emails I design has it's own folder aka "project". This is done for organization purposes. Each folder contains a header/index/footer.mjml. I would like to select these multiple folders (which show up as recent projects in MJML app), and export all of them. Screenshot of what my projects look like attached:

![image](https://user-images.githubusercontent.com/4194561/27092335-80da0b60-5028-11e7-99dd-3ac8b11d562a.png)

So maybe it could work by being able to multi-select by clicking multiple thumbnails and then press one button to export all, select the folder/export destination and then an html email is generated for each project in the destination folder.

**Comment by meriadec** [comment]
OK got it. Yep I think this is totally doable, and not very difficult to implement.
Question: what do you think will be the best:
- export each HTML file in the project directory
- or export all the HTML files in the same folder (with file popup, to choose)

Nice emails BTW :)

**Comment by dshastry** [comment]
Haha thanks! Couldn't build them without your awesome app ;)

I think it would work best to go with #2. So the flow would be

Click add/select button on thumbnails to select multiple emails -> click mass export button -> set project destination folder -> export

Because for option 1 we can do this currently by hitting the export html button. its a pain to manually move the HTML files into one folder later on. Extra step that we can eliminate!

**Comment by meriadec** [comment]
![export](https://user-images.githubusercontent.com/315259/27234826-ad5685c2-52be-11e7-84f3-3267504cd453.gif)

UX is not perfect but it works :)

**Comment by dshastry** [comment]
Yup! Functionality is great. Would it be possible to select the folder you want to export to on click of the button? Perhaps in a dialog box that pops up

![image](https://user-images.githubusercontent.com/4194561/27234909-60bbbc6c-5284-11e7-9526-61d36c7297fa.png)

**Comment by meriadec** [comment]
Yes that is happening, in fact :) but not really visible in gif (on my
machine, the pop-up goes on the side of the window)

Le 16 juin 2017 6:10 PM, "David Shastry" <notifications@github.com> a
écrit :

**Comment by dshastry** [comment]
Oh ok, cool. Sounds good!

**Comment by matthewahillman** [comment]
Siliar to this I'd love to be able to export to html for all the selected. Much like you can when going into each project and exporting to HTML, i'd love to be able to do this for multiple variants without going into each one but having the HTML export into the emails folder. I don't want my HTML separate from the rest of my images etc. :)
