### ISSUE TITLE
Discussion: Parse HTML & Convert to MJML Project

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#157]
@meriadec quick question. So a while back I used MJML App in order to create a template. I exported out an HTML version of this project and that was that. Today I realized that I've lost the project files and just have the HTML file. Since Mailjet's structure/tags are in the HTML is it possible to "reverse engineer" and get an .mjml project out of it by running it through something that can parse them?

I realize it's a total edge case and probably offers little value to the larger user set, but just curious on the possibilities.

**Comment by meriadec** [comment]
hey David, sorry to hear that, but unfortunately that's not possible.
It's like, un-cooking an egg, you know.

![egg](https://user-images.githubusercontent.com/315259/27490544-f8711eb6-583e-11e7-9e3c-9a0242c891a8.png)

**Comment by dshastry** [comment]
😂😂 Haha cool sounds good. I figured it was something like that but atleast now I know for sure!

**Comment by sathishkumar94** [comment]
Parse HTML & Convert to MJML Project 
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
We can able to implement this own module. 

First we need to create an architecture like, 

for input , div tag we consider as mj-text.

for image, we read the attributeTag and we use mj-image. 

For styles we can get the style and we update .

---------------------------------------------------------------------------
For MJML 4 we need to write code like,

<mjml>
<mj-head>..</mj-head>
<mj-container>
<mj-section>
//TO DO data logic here
</mj-section>
</mj-container>

-----------------------------------------------------------
if you follow this steps will get successful html to mjml conversion .

**Comment by meriadec** [comment]
@sathishkumar94 I don't really understand. Do you have some code to share ?

**Comment by QuietMonkey** [comment]
> Parse HTML & Convert to MJML Project
> 
> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >
> 
> We can able to implement this own module.
> 
> First we need to create an architecture like,
> 
> for input , div tag we consider as mj-text.
> 
> for image, we read the attributeTag and we use mj-image.
> 
> For styles we can get the style and we update .
> 
> For MJML 4 we need to write code like,
> 
> ```
> <mjml>
> <mj-head>..</mj-head>
> <mj-container>
> <mj-section>
> //TO DO data logic here
> </mj-section>
> </mj-container>
> ```
> 
> if you follow this steps will get successful html to mjml conversion .

Can you send an exemple?

**Comment by Hodakhosravi** [comment]
> Parse HTML & Convert to MJML Project
> 
> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >
> 
> We can able to implement this own module.
> 
> First we need to create an architecture like,
> 
> for input , div tag we consider as mj-text.
> 
> for image, we read the attributeTag and we use mj-image.
> 
> For styles we can get the style and we update .
> 
> For MJML 4 we need to write code like,
> 
> ```
> <mjml>
> <mj-head>..</mj-head>
> <mj-container>
> <mj-section>
> //TO DO data logic here
> </mj-section>
> </mj-container>
> ```
> 
> if you follow this steps will get successful html to mjml conversion .
what about style? class remain ass class?

**Comment by Hodakhosravi** [comment]
> Parse HTML & Convert to MJML Project
> 
> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >
> 
> We can able to implement this own module.
> 
> First we need to create an architecture like,
> 
> for input , div tag we consider as mj-text.
> 
> for image, we read the attributeTag and we use mj-image.
> 
> For styles we can get the style and we update .
> 
> For MJML 4 we need to write code like,
> 
> ```
> <mjml>
> <mj-head>..</mj-head>
> <mj-container>
> <mj-section>
> //TO DO data logic here
> </mj-section>
> </mj-container>
> ```
> 
> if you follow this steps will get successful html to mjml conversion .
**what about the style and class?**

**Comment by sseshachala** [comment]
I have not done this. This should be possible. If mjml to html is possible - we should be able to convert mjml to html. but requires some effort.

**Comment by vladiliescu** [comment]
For people finding this while googling `convert html to mjml`, you can totally do it using an LLM (i.e. GPT-4) -- "Here is an html email (it uses Mako templates for templating). Please convert it to mjml while keeping the Mako tags as well: ```...```"

**Comment by zebulonj** [comment]
GPT-4 can complete a rough conversion that maintains the essential layout of the page (I was pleasantly surprised), but in my experimentation with it the results are unpredictable and some formatting is lost.

**Comment by deathemperor** [comment]
I was able to convert using Cursor's Compose with Claude Sonnet 3.5
