### ISSUE TITLE
Save/Revert

### ISSUE THREAD

**Issue by jbickelhaupt** [mjmlio/mjml-app#158]
Could we add Save to the menu so that we can knowingly save specific states of a project? Would love to be able to save a project, add some code, evaluate the solution, and then choose to either save/update the current file or close/revert to a previous iteration. Instead, it's always saving whatever I have in there and I'm forced to be mindful about how far back I can go using Undo.

Ideally, it would contain similar menu links found in Adobe Photoshop and others—Save, Save As, and Revert.

Maybe some of this can be addressed in #155, but I feel like this may be a slightly different request. This is closer to the original request found in #138.

**Comment by meriadec** [comment]
Definitely a good point.

I'm currently re-writing the project page for ability to open tabs + better image preview (see [that branch](https://github.com/mjmlio/mjml-app/tree/refactor-project-page) and [that issue](https://github.com/mjmlio/mjml-app/issues/150)).

This one can be done after.

**Comment by meriadec** [comment]
closing in favor of https://github.com/mjmlio/mjml-app/issues/219
