### ISSUE TITLE
Feature Request : SASS Support

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#162]
I saw this asked on the MJML repo a while back, but I wanted to ask about Sass support specific to the desktop application as I think it's independent of the framework. It's becoming tedious to maintain styles once I have over 20 templates. I would love to be able to use SASS/SCSS in order to have control over the style in all of them via variables, mixins, etc. This in addition to the #154 (Mass export of emails) will be a lifesaver when doing updates across a whole number of templates such as color/font/etc. I have to regularly update over 50 templates and right now I do it by hand/copy-paste which is a total waste of time. 

When looking I found this GULP pipeline and not sure if it's of value : https://libraries.io/github/Daylon/hbs-mjml-seed

I can do it using GULP locally, but would be great if the functionality was natively available through the desktop app so others not as familiar on my team can use it as well. Maybe by including a base.scss via @import in the <mj-style> tag in the head of all emails. Thoughts?

**Comment by MateuszDabrowski** [comment]
On the other hand if you translate .scss to .mjml style part and then @import it in all of the templates the job is done with only updating one .mjml file that is later imported in all of your templates.

**Comment by dshastry** [comment]
That's fair point @MateuszDabrowski. I didn't think about it that way. I guess what I was also thinking, and why I brought it up is to keep the style separate from the structure. MJML is more about defining structure and SASS is purely style driven. also easier to split up sass into multiple files and call in via includes/imports but not sure if MJML would be able to handle multiple nested MJML file imports.

EG: I include master-styles.mjml in all my folders but inside of master-styles i have reset.mjml, fonts.mjml, colors.mjml, etc etc. Would my templates that reference master-styles.mjml pull in all the nested templates inside of it?

**Comment by meriadec** [comment]
I think including SASS _inside_ the app, despite adding a not negligible size to the app, will be out of the scope of the app, which focus on compiling MJML.

Nested mj-include should work, give it a try. If you need more complex pipelines you also can set-up a gulp pipeline (check out [gulp-mjml](https://github.com/mjmlio/gulp-mjml)) where you can include SASS compilation / CSS concatenation, etc.
