### ISSUE TITLE
Find & Replace

### ISSUE THREAD

**Issue by jbickelhaupt** [mjmlio/mjml-app#163]
Adding find & replace functionality would be awesome. Allowing users to find specific markup and jump to that point in the code would be helpful, as would allowing one to replace all instances of any particular code.

**Comment by meriadec** [comment]
Hey Jon, good news, this is already possible with the `Ctrl+Shift+R` binding :)

![export](https://user-images.githubusercontent.com/315259/27726371-86167352-5d7a-11e7-9f17-19c0bbebf31b.gif)

**Comment by jbickelhaupt** [comment]
Egg on my face. I guess I forgot about that as I didn't see it listed in any of the menus for the app. If there's a lot of "hidden" features that are not listed in the menu, it may be worth considering to add a link in there somewhere…

**Comment by meriadec** [comment]
That's very true!
