### ISSUE TITLE
Multiple e-mails paste into Send target

### ISSUE THREAD

**Issue by MateuszDabrowski** [mjmlio/mjml-app#164]
I tried to copy-paste list of spam-test emails from Litmus to the app, but it recognize them as one single e-mail. Had to copy paste one by one, 27 times. It would be great to add possibility to paste multiple addreses at once with semicolon or something.

**Comment by meriadec** [comment]
Will be available in 2.5.0

![export](https://user-images.githubusercontent.com/315259/28712502-ae58e530-738b-11e7-9b90-c8d9f707dc93.gif)
