### ISSUE TITLE
Feature Request: Mass export JPG/PNG

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#166]
The mass export of HTML by selecting templates works beautifully! It would be great if we can also include an export screenshot or export PNG button alongside, that will generate images into a chosen output folder.

Can this be done?

**Comment by meriadec** [comment]
Yeah, could be nice

**Comment by meriadec** [comment]
will be included in next release

**Comment by dshastry** [comment]
Thanks for the quick turnaround! @meriadec, you're awesome!
