### ISSUE TITLE
Multiple Project Tabs/Windows

### ISSUE THREAD

**Issue by jbickelhaupt** [mjmlio/mjml-app#170]
It would be AWESOME if you could have additional tabs or windows open with multiple MJML projects open. I often pull up two sets of email code and copy & paste certain elements. I also use it to compare code when troubleshooting.

**Comment by jbickelhaupt** [comment]
Sorry. Just found this referenced in #150. Knew I had seen someone else ask this before! :)

**Comment by MateuszDabrowski** [comment]
+1, especially considering that switching between two .mjml files in app means need of scrolling to the right part everytime as there is no scroll memory. Two tabs would solve the issue.
