### ISSUE TITLE
Cant get into MJML app and I'm getting this message. I don't know what to do! 

### ISSUE THREAD

**Issue by victorsana** [mjmlio/mjml-app#171]
TypeError: Expected Array or iterable object of values: [object Object]
    at U (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:5:301230)
    at R (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:5:300522)
    at r (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:5:299056)
    at Be (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:5:308861)
    at e (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:25:323018)
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:25:150512
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:37:222157
    at Array.reduce (native)
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:37:222129
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:37:224705
    at e (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:37:229556)
    at u (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:25:151965)
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:37:131300
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:37:226118
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:25:293118
    at e (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:37:226428)

**Comment by meriadec** [comment]
Hi @victorsana , that's strange :| What OS are you using?
Can you try re-downloading the latest version from here: https://github.com/mjmlio/mjml-app/releases

**Comment by victorsana** [comment]
Hey @meriadec I'm using macOS Sierra. I re downloaded the app and am having the same problem.

**Comment by meriadec** [comment]
Can you try deleting the app settings? The file should be located here:

```
~/Library/Application\ Support/Electron/storage/settings.json
```

**Comment by meriadec** [comment]
@victorsana do you still have the issue?

**Comment by GrzegorzCupial** [comment]
Hi, i've got the same issue. I don't know what happened. It worked yesterday

TypeError: Expected Array or iterable object of values: [object Object]
    at U (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:18:60107)
    at A (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:18:59399)
    at r (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:18:57933)
    at Be (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:18:67738)
    at e (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:47:438000)
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:18:286460
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:41:14067
    at Array.reduce (<anonymous>)
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:41:14039
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:41:13809
    at e (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:25:360481)
    at p (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:18:233176)
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:25:389154
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:47:436961
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:47:440300
    at e (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:25:361369)


Can't find Electron folder

**Comment by meriadec** [comment]
Hello @GrzegorzCupial , can you confirm that the problem occurs in the version 2.7.0 ? If you have an anterior version, you can download 2.7.0 from here: https://github.com/mjmlio/mjml-app/releases/tag/2.7.0.

If the problem persists, you can reach me on the [MJML Slack](https://slacking-inviter.herokuapp.com/).

**Comment by GrzegorzCupial** [comment]
![zrzut ekranu 2017-10-25 o 10 38 03](https://user-images.githubusercontent.com/20965336/31988823-aae1e8ae-b970-11e7-88bb-af554a8ed989.png)

I've found storage folder and deleted settings.json
It helped, thanks :)

**Comment by meriadec** [comment]
OK good news. But it also means that [my fix](https://github.com/mjmlio/mjml-app/commit/c2d6365c81373d7db6f64ddb50c3cc65cdb31dbd) wasn't enough to handle the problem. Arf.

**Comment by ngarnier** [comment]
I think the Electron folder is here when you use the app in dev mode only. When you run the MJML App as a normal app, you need to delete the `settings.json` file in `Library/Application\ Support/MJML/storage`. 

Steps to do so: 

1. Open a terminal (Press "⌘+Space" on your keyboard to open Spotlight, then type "Terminal" and press Enter)
2. Paste `cd Library/Application\ Support/MJML/storage ` and press Enter
3. Paste `rm -rf settings.json` to delete the settings file*

This will clear the settings of the MJML App, which means next time you open the app, it will be like the first time you opened it (the app won't remember your projects' folders). However, **you won't lose** any MJML template you worked on.

*Alternatively, you can try to fix the file structure, which should look like this: 

```js
{
    "lastOpenedFolder": "path to your last opened folder",
    "projects": ["array of projects' paths"],
    "editor": {
        "wrapLines": true,
        "autoFold": false,
        "foldLevel": 1,
        "highlightTag": false,
        "lightTheme": false
    },
    "api": {
        "Subject": "MJML App test email",
        "APIKey": "",
        "APISecret": "",
        "SenderName": "MJML App",
        "SenderEmail": "",
        "TargetEmails": [],
        "LastEmails": []
    },
    "mjml": {
        "minify": false,
        "beautify": false
    },
    "previewSize": {
        "current": 500,
        "mobile": 320,
        "desktop": 650
    }
}
```

**Comment by victorsana** [comment]
@meriadec @GrzegorzCupial @ngarnier thank you so much for your help. i'm going to try this and see if it works :)

**Comment by meriadec** [comment]
should be fixed in 2.8.0

**Comment by victorsana** [comment]
@meriadec solved!! Thank you so much

**Comment by meriadec** [comment]
Glad you figured out so quickly lol
