### ISSUE TITLE
Feature Request: Doctype Declaration Control

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#173]
One of the issues recently raised by one of the members on my team has been that when I hand off emails for implementation into other systems (CRM/Salesforce/etc) we are getting some issues because the doctype is being declared twice. We noticed that the CRM we use has tinymce that automatically declares the doctype on all html content. However, MJML is also declaring a doctype in its html (as expected). Because of the two doctypes, one gets shown as plaintext at the top of the email, and has to be removed by hand each time. This just adds one more step to our process.

Would it be possible to add a checkbox option/toggle to prevent declaring doctype on exported HTML? Would be very helpful to users exporting from MJML into third party software.

**Comment by meriadec** [comment]
@iRyusa do you think that would be implementable as an option in MJML?

**Comment by iRyusa** [comment]
Well Doctype is a "core" element for the output HTML(altering it can totally change a client behavior see https://emails.hteumeuleu.com/which-doctype-should-you-use-in-html-emails-cd323fdb793c) , it looks more an issue on workflow side than MJML side.

I don't really understand why MJML would provide such an option for an edge case. 

An easy fix on your side is to use an easy gulp task like gulp replace and remove the doctype.

**Comment by meriadec** [comment]
That's right, it's more related to specific cases where doctype is added by third-parties.
@dshastry you may want to implement you own build pipeline to remove doctype, as the "problem" is due to tinymce, not to MJML/MJML App itself.
