### ISSUE TITLE
Removing files from App

### ISSUE THREAD

**Issue by MateuszDabrowski** [mjmlio/mjml-app#174]
For some time I'm not able to remove any file via app on OSx. 
Clicking x gives me context menu but confirming removing closes the pop up and nothing happens - must delete files via Finder.

Renaming works just fine. Removing projects also works just fine. Only files are issue.
MJML App v2.6.0

**Comment by meriadec** [comment]
hey @MateuszDabrowski , is it still an issue on 2.7 ?

**Comment by MateuszDabrowski** [comment]
@meriadec Unfortunaltelly yes, problem persist. After attached screen nothing happens:
![screen shot 2017-10-05 at 11 00 39](https://user-images.githubusercontent.com/13339456/31219098-91b8b3bc-a9bc-11e7-951f-8631c57ff0e5.png)

**Comment by meriadec** [comment]
Ok! will investigate
