### ISSUE TITLE
Hardcoded "MJML App" as sender name

### ISSUE THREAD

**Issue by Mistra** [mjmlio/mjml-app#175]
As for title (in sendEmail.js:12); woudn't it be nicer if you could allow people to choose the sender's name? One can chance it anyway in the code and recompile.

I volunteer to code the option in settings (maybe leaving MJML App as default), just let me know if such thing can be accepted before I start working on it.

Thank you

**Comment by meriadec** [comment]
Hey @Mistra, good idea!
Here is some hints to help you work:

- base yourself on the develop branch
- add `SenderName` with default in [actions/settings.js](https://github.com/mjmlio/mjml-app/blob/c2d6365c81373d7db6f64ddb50c3cc65cdb31dbd/app/actions/settings.js#L38)
- in `SendModal`:
  - load it: [pages/Project/SendModal.js](https://github.com/mjmlio/mjml-app/blob/c2d6365c81373d7db6f64ddb50c3cc65cdb31dbd/app/pages/Project/SendModal.js#L23)
  - pass it [in prop](https://github.com/mjmlio/mjml-app/blob/c2d6365c81373d7db6f64ddb50c3cc65cdb31dbd/app/pages/Project/SendModal.js#L33)
  - create the [state key](https://github.com/mjmlio/mjml-app/blob/c2d6365c81373d7db6f64ddb50c3cc65cdb31dbd/app/pages/Project/SendModal.js#L56)
  - make it [update with props](https://github.com/mjmlio/mjml-app/blob/c2d6365c81373d7db6f64ddb50c3cc65cdb31dbd/app/pages/Project/SendModal.js#L132)
  - allow it [to be saved in config](https://github.com/mjmlio/mjml-app/blob/c2d6365c81373d7db6f64ddb50c3cc65cdb31dbd/app/pages/Project/SendModal.js#L143)
  - get it from state and pass it to `sendEmail` [here](https://github.com/mjmlio/mjml-app/blob/develop/app/pages/Project/SendModal.js#L103)
  - pass it in prop to `MailjetInfos` in [render](https://github.com/mjmlio/mjml-app/blob/c2d6365c81373d7db6f64ddb50c3cc65cdb31dbd/app/pages/Project/SendModal.js#L182) to make it editable
- in `MailjetInfos`:
  - make MailjetInfos open directly if `SenderName` missing [in state.isOpened](https://github.com/mjmlio/mjml-app/blob/develop/app/components/MailjetInfos.js#L10)
  - create input block for `SenderName`, [like that](https://github.com/mjmlio/mjml-app/blob/develop/app/components/MailjetInfos.js#L88-L100)
in `helpers/sendEmail.js`, [use SenderName](https://github.com/mjmlio/mjml-app/blob/c2d6365c81373d7db6f64ddb50c3cc65cdb31dbd/app/helpers/sendEmail.js#L4)

Maybe I miss some little things, so don't hesitate to ping me if needed :)

**Comment by Mistra** [comment]
Ok, I basically did exactly that yesterday night, but I completly missed the dev branch. As soon as I got time I rebase and push.
Comments in the code: any preference?

**Comment by meriadec** [comment]
ahah nice :) sounds good!
for comments, no real preferences! if it's clear things, it's good.
