### ISSUE TITLE
Black Screen app

### ISSUE THREAD

**Issue by BillyB0y** [mjmlio/mjml-app#18]
When i launch the binary (MJML.app) builded from source as described in README.md, i've got a black window, nothing else. 
OS X 10.11.4

**Comment by GuillaumeBadi** [comment]
Hey @BillyB0y !

It looks like an MJML issue. Can you set the `"mjml"` package version to `1.2.1` in your `package.json` and restart the installation?. Should be working fine 

Best,
Guillaume

**Comment by GuillaumeBadi** [comment]
Please reopen if it didnt fix the problem
