### ISSUE TITLE
2.7.0 is detected as threat in Avast Antivirus

### ISSUE THREAD

**Issue by chbj** [mjmlio/mjml-app#186]
The Windows version 2.7.0 is detected as a threat by Avast Antivirus software.

**Comment by meriadec** [comment]
lol :joy: 

is there any explanation?

**Comment by chbj** [comment]
I know :-D
No explanation, just that it has successfully removed and blocked the threat.

I had no issues downloading and installing 2.6.0

**Comment by meriadec** [comment]
sounds related to electron-packager (see https://github.com/electron-userland/electron-builder/issues/1870). I'm not really aware about code-signing on Windows :(

**Comment by meriadec** [comment]
reading people comments, it can even be related to avast itself :upside_down_face:

**Comment by chbj** [comment]
I wouldn't be surprised of it was :-P Going to hold my breath for an Avast update in the coming future then. Alternatively I'll to to install it from a thumb drive Monday.
Thanks for looking into it.

**Comment by ngarnier** [comment]
Hey hey, I don't have Avast installed but I get the same warning message from Windows defender. I tried building 2.7.1 and got no issue to run it, so it might be indeed related to using a VM @meriadec. 

Should I upload the v2.7.1 .exe after you make the proper release?

**Comment by meriadec** [comment]
Thanks @ngarnier :) yes, as discussed irl, would be awesome if you could replace the actual 2.7.0 windows build by a fresh one (even built on 2.7.1, doesn't really matter, the only difference is a minor deps update + a typo fix)

**Comment by ngarnier** [comment]
Well, no luck here. After uploading the Windows-built version and then redownloading it, Windows defender is blocking it again... So it seems it's not related to the fact it was built on a VM but rather to the issue you linked previously (https://github.com/electron-userland/electron-builder/issues/1870)
