### ISSUE TITLE
Help: Use custom MJML engine

### ISSUE THREAD

**Issue by pvlachou** [mjmlio/mjml-app#187]
Hi,

Probably not an issue with the app, more so with me :)

I've installed mjml globally on my system (OSX), without issue. Running mjml commands in Terminal and it's all good. The mjml executable is found in **/usr/local/lib/node_modules/mjml/bin**/

Trying to setting up the custom engine using the path above, but it keeps saying "MJML not found at this location".

What am I doing wrong?

Thanks,
Paul

**Comment by meriadec** [comment]
Hello @pvlachou , yes there is an issue with the OSX version for the custom MJML engine *only in builded mode* -> the system can't find the executable. But it works fine in dev environment.

If you are motivated enough, you can use the app in dev mode (see README for instructions ^^), until I figure out what's happening.

**Comment by thedamianmason** [comment]
Even with dev mode (using macOS High Sierra) the preview never shows using 4.0 as the engine, but will being to preview with 3.3.5 although it still never fully rendered after an hour.

**Comment by kmcb777** [comment]
Custom engine use is fully operational in the latest version (only with v4 engines) so we can close this one
