### ISSUE TITLE
Cannot open app on Mac

### ISSUE THREAD

**Issue by simonkrabbe** [mjmlio/mjml-app#188]
I get the following error message:

TypeError: Expected Array or iterable object of values: [object Object]
    at U (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:18:60107)
    at A (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:18:59399)
    at r (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:18:57933)
    at Be (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:18:67738)
    at e (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:47:438000)
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:18:286460
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:41:14067
    at Array.reduce (<anonymous>)
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:41:14039
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:41:13809
    at e (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:25:360481)
    at p (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:18:233176)
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:25:389154
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:47:436961
    at file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:47:440300
    at e (file:///Applications/MJML.app/Contents/Resources/app.asar/dist/bundle.js:25:361369)

Any help would be greatly appreciated :)

Simon

**Comment by meriadec** [comment]
Hello @simonkrabbe , sorry for the inconvenience :( 

Your issue is similar to https://github.com/mjmlio/mjml-app/issues/171.
You can resolve the problem by removing the `settings.json` file.

It is located here:

```
[Your home folder] > Library > Application Support > Electron > storage > settings.json
```

Thanks to close the issue if this resolved your problem.
I will try to make a patch in the next version.

To help me find the problem, can you attach the `settings.json` file to the issue, before removing it?

**Comment by thedamianmason** [comment]
Same issue. I cannot find any Electron directory.
on 2.7.1

**Comment by meriadec** [comment]
@thedamianmason so you see the Library folder but not Electron ? maybe some folders are hidden.

here is how you can show hidden files: https://www.macworld.co.uk/how-to/mac-software/how-show-hidden-files-library-folder-mac-3520878/

**Comment by thedamianmason** [comment]
Still nothing there. I did a system search and the closest match is /electron-json-storage/lib/storage.js

**Comment by thedamianmason** [comment]
I can still use the app error free by running the yarn dev environment.

**Comment by thedamianmason** [comment]
Maybe this will help. 
When compiling I see this...
![screen shot 2017-11-03 at 2 46 38 pm](https://user-images.githubusercontent.com/28071685/32390822-45454274-c0a6-11e7-9be6-9faa253602a7.png)

**Comment by pc1oad1etter** [comment]
I also have this error.  FWIW, I installed MJML using homebrew on my Mac.  I found ~/Library/Application Support/MJML/storage/settings.json .  I'm attaching the file.  When I open it in Atom the syntax doesn't highlight everything, but I checked it in a JSON validator and it seems to be valid.  

[settings.json.zip](https://github.com/mjmlio/mjml-app/files/1521138/settings.json.zip)
