### ISSUE TITLE
MJML App reported as malware by AV

### ISSUE THREAD

**Issue by dphi76** [mjmlio/mjml-app#189]
My IT department is telling me that the installer for the MJML app is reported as malware by their anti-virus suite and is not allowing us to install it. 

I realize it's not, but can you please advise me what I should tell them?

Here is a screenshot of the warning:

![mjml-warning](https://user-images.githubusercontent.com/33334011/32354699-18568052-bfe8-11e7-942c-e417aa0b2e66.png)

**Comment by meriadec** [comment]
hey @dphi76, sounds related to https://github.com/mjmlio/mjml-app/issues/186.
Can you try with version 2.6.0 ? (download it here: https://github.com/mjmlio/mjml-app/releases/tag/2.6.0) and say if you also have the problem?

I will contact Avast to flag it at false positive.

**Comment by dphi76** [comment]
Thank you. Can you also contact Trend Micro to have it whitelisted as well? That's the security package our organization uses.

**Comment by meriadec** [comment]
is the issue still a thing?
