### ISSUE TITLE
App Randomly Crashes When Simply Editing 

### ISSUE THREAD

**Issue by seahawksean** [mjmlio/mjml-app#190]
Twice in the past 15 minutes the MJML app (2.7.0) seems to crash when I'm simply editing the email I'm working on.  I just start typing in the code section and suddenly the app window goes blank.  

![screen shot 2017-11-08 at 9 17 47 am](https://user-images.githubusercontent.com/410327/32553975-54b74d4c-c466-11e7-9871-b2b613c8f886.png)

In order to get the app working again, I have to quit the app and open it back up.  Not the end of the world, but thought you might want to know about the possible bug.

I'm on Mac OS X 10.13 High Sierra.

**Comment by meriadec** [comment]
Hi, thx for reporting, despite this kind of bug can be hard to reproduce. Would you mind attaching a mjml file that produce the crash?

**Comment by seahawksean** [comment]
I would love to but .mjml format isn't a supported file here. lol

**Comment by seahawksean** [comment]
Here's my workaround.  Added it here as a .zip file.
[ldmQuoteConfirmation.mjml.zip](https://github.com/mjmlio/mjml-app/files/1455087/ldmQuoteConfirmation.mjml.zip)

**Comment by davelantto** [comment]
I've had this problem starting today too, the app (2.7.0 installed Sept 29th) was working fine before. Noticed I ran a macOS security update 2017-001 on Nov 1st, wonder if that's what's causing the problem? I'm on Sierra 10.12.6. Restarting the app seems to work, but after 15-20 minutes it'll crash again. Thanks

**Comment by meriadec** [comment]
losing for now. feel free to re-open if pb persists
