### ISSUE TITLE
Switch button between desktop and mobile view prevents links to be clickable

### ISSUE THREAD

**Issue by ddeath** [mjmlio/mjml-app#191]
When you have email links in position next to the switch button they are not clickable.

In this case "blogu" is not clickable.

![non_clickable](https://user-images.githubusercontent.com/2537379/32979322-413a5abc-cc53-11e7-8e06-1c887a9d91e7.png)

Not a big deal, just mentioning it :)

**Comment by meriadec** [comment]
Hi @ddeath, the code is here: https://github.com/mjmlio/mjml-app/blob/7ebabf3f8708552b15e6222f5661db19da5df60f/app/components/FilesList/FilePreview.js#L34-L55 I think it can be pretty easily solved by adding [pointer-events: none](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events), to the container, then`pointer-events: auto` to the buttons. That will allow clicks to pass through transparent container.
