### ISSUE TITLE
New file feature does not respects subfolders

### ISSUE THREAD

**Issue by ddeath** [mjmlio/mjml-app#192]
* open project
* create subfolder A in it
* open A
* click on New file
* enter the name for the file
* hit Create file
* file is created in project root and not in subfolder

**Comment by meriadec** [comment]
File creation is done here: https://github.com/mjmlio/mjml-app/blob/4061c636a0f892210e4dc4bf529415e6873fc450/app/pages/Project/index.js#L87 so to make new file be created on the selected folder, it will need to take it in account at this moment (using `state.activeFile` or `state.path` (to be tested)
