### ISSUE TITLE
Visual Code Indicator for Preview

### ISSUE THREAD

**Issue by jbickelhaupt** [mjmlio/mjml-app#195]
I know we can't match the same experience as Adobe Dreamweaver or others by clicking on a visual element in the preview screen and then having it highlight or jump to the corresponding MJML code in the code window. But how about some kind of cursor or visual indicator that shows up in the preview that corresponds to what piece of code you're scrolling through or editing?

I think this would help those that are getting lost in what piece of code they're looking at and where it gets rendered in the visual layout of the email. If it seems too distracting or makes it easier to come up with a solution, maybe offer a toggle switch to turn the feature on and off? If you go with a toggle switch, I'd keep it immediately available as you code/preview your email—not buried in the app settings.

**Comment by meriadec** [comment]
Closing for now. May be reconsidered if there is some serious & robust technical solutions is suggested, because it will probably imply serious investment & testing.
