### ISSUE TITLE
Main available download is 2.6.0

### ISSUE THREAD

**Issue by tiennou** [mjmlio/mjml-app#196]
It seems the release served [here](https://mjmlio.github.io/mjml-app/) for Mac users is 2.6.0, even though it says 2.7.0.

Later, when you launch the app, you get an "There is a new version available! (2.7.0)" notification, which sends your back to that page, downloading 2.6.0 again.

I can see that the 2.7.0 release is also available on GitHub so I'll use that anyway 😉 . HTH !

**Comment by meriadec** [comment]
hey @tiennou , the 2.7.0 version was leading many problems on OSX (see [here](https://github.com/mjmlio/mjml-app/issues/194) or [here](https://github.com/mjmlio/mjml-app/issues/188)) so I deleted it from the releases.

Any help to debug the problem would be very appreciated !

**Comment by iamandrewluca** [comment]
@meriadec I made a build on my machine and everything works fine. Also first issue you mentioned is Windows related.

**Comment by rinopo** [comment]
Downloaded 2.7.0 a while ago, and it's working fine on my Mac (Sierra 10.12.6).

**Comment by iamandrewluca** [comment]
@meriadec , please add release back for osx. Homebrew cask fails for 2.7.0
