### ISSUE TITLE
MJML App not updating on Mac

### ISSUE THREAD

**Issue by maherelaridi** [mjmlio/mjml-app#197]
Hi, 

I am having trouble updating my MJML app on my mac. The download button in the notification section does not trigger anything. 

Currently using MJML App v2.4.0 and MJML v3.3.3. Anyone having the same issue?

Thanks so much in advance!

<img width="450" alt="screenshot 2017-12-20 14 18 02" src="https://user-images.githubusercontent.com/2089136/34227047-60297668-e591-11e7-9557-336d21ac6752.png">
<img width="374" alt="screenshot 2017-12-20 14 18 10" src="https://user-images.githubusercontent.com/2089136/34227048-6037ef7c-e591-11e7-951c-ba8f57228704.png">

**Comment by meriadec** [comment]
Hey there, you can download it manually [from the release page](https://github.com/mjmlio/mjml-app/releases). As there is some issues with the 2.7.0 on Mac, the last version for Mac is 2.6.0 (see https://github.com/mjmlio/mjml-app/issues/196).

**Comment by maherelaridi** [comment]
Thanks @meriadec! Downloaded 2.8.0 and it works like a charm
