### ISSUE TITLE
App still using Mjml 3.3.3

### ISSUE THREAD

**Issue by justlevine** [mjmlio/mjml-app#198]
Noticed that v2.7.1 is still using an old version of MJML (3.3.3). Any plans for an update to 3.3.5? Alternatively, is there a way to manually update it?

**Comment by nicolas-besnard** [comment]
You can install `3.3.5` on you machine and use the `Use a custom MJML engine` in the options menu :)

**Comment by meriadec** [comment]
now mjml-app uses mjml 4

https://github.com/mjmlio/mjml-app/releases/tag/v2.8.0
