### ISSUE TITLE
App .dmg 2.7.0 not available

### ISSUE THREAD

**Issue by snHolst** [mjmlio/mjml-app#199]
Hey,

on your website the link for version 2.7.0 will be displayed as download. However, you only get the 2.6.0 version as a download. Should that be so or is this a mistake? Unfortunately, here in Github the .dmg for the 2.7.0 is not available for download what is going on? best regards
 
<img width="650" alt="bildschirmfoto 2017-12-22 um 22 07 05" src="https://user-images.githubusercontent.com/11442037/34312445-7f2c5768-e764-11e7-94e5-604ee5e57285.png">

**Comment by ngarnier** [comment]
Hey @snHolst, indeed v2.7.0 was removed, please use v2.6.0 (see https://github.com/mjmlio/mjml-app/issues/196#issuecomment-352703548)
