### ISSUE TITLE
Including multiple files does not work

### ISSUE THREAD

**Issue by snHolst** [mjmlio/mjml-app#201]
We once set up separate areas.
There is an index.mjml, this includes a header.mjml, content.mjml and footer.mjml. If now the <mjml> tag is not set in the index.mjml but in the header.mjml, then the index.mjml does not completely compile all data together. The same happens with the footer.

Why does this not work?!

**Comment by ngarnier** [comment]
Just tried adding a header and a footer and it works correctly. 

Please share some details so we can actually help you: 

-  code
- version of the app you use
- any information needed to reproduce your problem

**Comment by snHolst** [comment]
this is not what i mean... in your screenshot the tag from <mjml> to </mj-header> put this in your header.mjml and then it doesnt work. in the index.mjml they are online the include files for header.mjml and footer.mjml...

**Comment by meriadec** [comment]
Please share a reproducible example of the problem.

**Comment by snHolst** [comment]
here you can see it... the header is not displayed...

![bildschirmfoto 2018-01-02 um 14 19 24](https://user-images.githubusercontent.com/11442037/34484893-faf172c8-efc7-11e7-81a0-8a79ead11b65.png)

**Comment by ngarnier** [comment]
Indeed, you can't cut the MJML needed structure like 

top.mjml
```
<mjml>
  <mj-body>
    <mj-container>
```
and 

bottom.mjml
```
    </mj-container>
  </mj-body>

</mjml>
```

However you can achieve exactly what you want by doing this: 
```
<mjml>
  
  <mj-include path="./head.mjml" />

  <mj-body>
    <mj-container>
      
      <mj-include path="./content.mjml" />
      
      <mj-include path="./footer.mjml" />

    </mj-container>
  </mj-body>

</mjml>
```

**Comment by snHolst** [comment]
I have already found out. But how can I finally finish only the header and footer separated from each other to export?

**Comment by snHolst** [comment]
With this structure, that's just not possible.

**Comment by ngarnier** [comment]
To be more precise about my last comment: you can, but you need at least this in your index.mjml: 
```
<mjml>
you can include anything here
</mjml>
```

I have no idea of what you have in your header and footer files as you haven't shared the content like we asked.

**Comment by snHolst** [comment]
This way works weirdly.

![bildschirmfoto 2018-01-02 um 14 33 56](https://user-images.githubusercontent.com/11442037/34485302-255192f8-efca-11e7-911c-daed0a4f5862.png)
![bildschirmfoto 2018-01-02 um 14 34 04](https://user-images.githubusercontent.com/11442037/34485303-256aec44-efca-11e7-8661-62ca5f7b860b.png)

**Comment by snHolst** [comment]
But I try again your suggestion.
