### ISSUE TITLE
Blanck Screen after send a test email 

### ISSUE THREAD

**Issue by YanisVmed** [mjmlio/mjml-app#203]
MJML App 2.7.1
MJML v3.3.3

Firstly I want to say that your application is just fantastic!
However, after sent an email with the "Send" function of your application, MJML app crash and just display a blank screen, as shown in the attached image.

![prtscr capture_3](https://user-images.githubusercontent.com/28859581/35741710-c1061aee-0838-11e8-9c31-ad21d0291cb6.jpg)

**Comment by ngarnier** [comment]
Hey @YanisVmed, thanks for the kind words! 

Can you reproduce consistently this bug consistently, or does it happen randomly?
Also, does it happen with one template in particular (if so, can you please share the template), or with all of your templates?

**Comment by YanisVmed** [comment]
Hey!
Yes, this error appears shortly after I have used a test mailing to different emails with your "send" function of MJML App, namely that the mails sent are well received and well integrated.
For the template I used the "Single File, Basic Layout" and then I added my own code, here it is:

`<mjml>
  <mj-head>
    <mj-font name="Nunito" href="https://fonts.googleapis.com/css?family=Nunito" />
    <mj-attributes>
      <mj-all font-family="Nunito, Arial" />
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-container background-color="#fff">

      <mj-section>
        <mj-column>
          <mj-image href="https://takidex.fr/" src="image url api" width="200px"></mj-image>
        </mj-column>
      </mj-section>

      <mj-section background-color="#75497f">
        <mj-column>
          <mj-text align="center" color="#fff" font-size="24px" line-height="1.3" font-weight="bold" text-transform="uppercase">
            oBJET : Validation Inscription
          </mj-text>
        </mj-column>
      </mj-section>

      <mj-section>
        <mj-column>
          <mj-text>
            <h1 style="font-size:18px; font-weight:normal;">Bonjour [Civility] [FirstName] [LastName],</h1>
            <p>Vous avez demandé récemment à vous inscrire à <a href="https://docteurd.fr/" style="color:#5bc0de;">DocteurD.fr</a>. DocteurD utilise le système d’authentification Takidex pour vérifier votre profil..</p>

            <p>Nous vous informons que votre inscription à <a href="https://docteurd.takidex.fr/" style="color:#5bc0de;">Takidex.fr</a> vient d'être <b>validée.</b></p>

            <p>Vos identifiants sont les suivants :</p>

            <p><b>Email : </b>[Email]</p>
            <p><b>Mot de passe : </b>Celui que vous avez indiqué lors de votre inscription.</p>

            <p>Vous pouvez désormais accéder à <a href="https://docteurd.fr/" style="color:#5bc0de;">DocteurD.fr</a> en cliquant sur le bouton suivant.</p>
          </mj-text>
          <mj-button background-color="#75497f" color="white">
            DocteurD.fr
          </mj-button>
          <mj-text>
            <p>Veuillez noter que le lien ci-dessus vous permettra de vous connecter automatiquement pendant 1 semaine. Passé ce délai vous devrez utiliser votre email/mot passe pour accéder au site.</p>
            <p>En cas de problème vous pouvez nous contacter au 01 55 60 98 52.</p>
            <p>A bientôt sur <a href="https://takidex.fr/" style="color:#5bc0de;">Takidex.fr</a>.</p>
            <p>Service d’inscription de Takidex</p>

          </mj-text>
          <mj-divider border-width="1px" border-style="solid" border-color="lightgrey" />
          <mj-text>
            <small>Vous disposez d'un droit d'accès, de modification, de rectification et de suppression des données vous concernant (loi "informatique et libertés" du 6 janvier 1978 modifiée). Pour toute demande relative à vos données personnelles, nous vous remercions de vous adresser au Responsable des Données Personnelles de VMed, 86 rue Thiers, 92100 Boulogne Billancourt. Vous pouvez également consulter nos conditions génerales d’utilisation à l’adresse suivante : <a href="https://docteurd.takidex.fr/cgu" style="color:#000;text-decoration: none;">https://docteurd.takidex.fr/cgu</a>.</small>
          </mj-text>
        </mj-column>
      </mj-section>

    </mj-container>
  </mj-body>
</mjml>`

In addition, I am under windows 10 family x64.

**Comment by YanisVmed** [comment]
<mjml>
  <mj-head>
    <mj-font name="Nunito" href="https://fonts.googleapis.com/css?family=Nunito" />
    <mj-attributes>
      <mj-all font-family="Nunito, Arial" />
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-container background-color="#fff">

**Comment by ngarnier** [comment]
This sounds like a similar issue with the 2.7.0 version: https://github.com/mjmlio/mjml-app/issues/190. 

Could you try to downgrade to 2.6.0 and see if it still happens? https://github.com/mjmlio/mjml-app/releases/tag/2.6.0

**Comment by YanisVmed** [comment]
Yes it works with this version, I do not have the error anymore. Curious...

**Comment by meriadec** [comment]
2.7.0 looks definitely crappy :upside_down_face:

**Comment by YanisVmed** [comment]
With the last version MJML App v2.8.0, this bug is fixed. 

**Thanks !**
