### ISSUE TITLE
download link says 2.7.0 but it downloads 2.6.0

### ISSUE THREAD

**Issue by timc13** [mjmlio/mjml-app#206]
The update notification in the app also links to 2.6.0

**Comment by meriadec** [comment]
Hey, the 2.7.0 have lead to multiple problems (see https://github.com/mjmlio/mjml-app/issues/194, https://github.com/mjmlio/mjml-app/issues/204, https://github.com/mjmlio/mjml-app/issues/194) especially on Mac, so the osx version has been removed from 2.7.0 release. You can safely ignore the notification. We plan a 2.8.0 release to fix those issues.
