### ISSUE TITLE
Windows Build for latest release

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml-app#21]
The latest is 1.10.
Can't compile this at work, would be ncie to always be up to date.

**Comment by GuillaumeBadi** [comment]
Hey @janus-reith 

The previous windows build was provided by a community member.. pretty hard to build it on my mac. I will try it at home tonight! 

I'll keep you up to date

**Comment by janus-reith** [comment]
Awesome, thanks for the effort you put into this!

**Comment by GuillaumeBadi** [comment]
The windows build doesn't look great from my mac, @meriadec , could you build it from your windows machine ? :D

**Comment by janus-reith** [comment]
node-gyp made problems for me. Sad that we can't just use MinGW gcc to build for Windows...

**Comment by meriadec** [comment]
Ok, I "succeeded" to build on my Windows (ahaha). Image generation seems to not work, but the other features works well. I have no time to investigate (and even more, investigate or an hostile OS ^^) check the [latest release](https://github.com/mjmlio/mjml-app/releases/tag/1.1.2).
