### ISSUE TITLE
The long awaited MJML 4 is here.

### ISSUE THREAD

**Issue by hansnolte** [mjmlio/mjml-app#213]
First of all, a heartfelt thank you for the MJML App.
I am looking forward to seeing the 4.0 in your MJML App.
Can't wait to try it!

Best regards
Hans

**Comment by meriadec** [comment]
Thank you! Your waiting will end soon, as we plan to release [mjml-app 2.8.0](https://github.com/mjmlio/mjml-app/pull/212) (which use MJML@4) in less than a week. :calendar: :eyes:

**Comment by hansnolte** [comment]
Hi meriadec ,

this is terrific!
I am very much looking forward.

Many greetings
Hans

**Comment by hansnolte** [comment]
Wow, that was fast!

Many thanks for 2.80

**Comment by dshastry** [comment]
@meriadec, thanks for updating but for some reason my MJML 3 templates are not working anymore. Is there a way to port old templates to new? Or maybe allow user to select older engine from the app?
