### ISSUE TITLE
<mj-font> not working anymore since v2.8.0

### ISSUE THREAD

**Issue by Razinsky** [mjmlio/mjml-app#215]
Hi, it seems that the latest release 2.8.0 now ignores `<mj-font />` tags? Is it related to MJML 4 ?

Please advise.

**Comment by meriadec** [comment]
I just tested [in try-it-live](https://mjml.io/try-it-live/rkFQpDh_f) and reproduced the issue, so yes, sounds like a MJML 4 issue.

You can find older version of the app here: https://github.com/mjmlio/mjml-app/releases

You may want to open an issue in [the MJML repo](https://github.com/mjmlio/mjml).
Have a good day

**Comment by Razinsky** [comment]
I just realized that the problem is not with `<mj-font />` being ignored but with the fact that now something like `<mj-all font-family="Arial" />` seems to override other font-family styles.

**Comment by meriadec** [comment]
Oh okay, glad that you sorted it out!
I'm not sure why my example in try-it-live is not loading font, but, eh ¯\_(ツ)_/¯

**Comment by Razinsky** [comment]
Haha great. But isn't it a bit weird that `<mj-all />` will override styles? Shouldn't it be like the latest fallback instead? Maybe again it's more of a MJML issue? Anyway thanks for support!

**Comment by meriadec** [comment]
Yep as you said, more MJML related!
You can discuss it either directly on github or on the MJML slack https://slacking-inviter.herokuapp.com/
