### ISSUE TITLE
Preview dont works

### ISSUE THREAD

**Issue by gnegreiros** [mjmlio/mjml-app#216]
Hello, the preview panel dont works, its empty. 

Reproduction Steps:

I opened my mjml project in mjml app on mac (app version 2.8.0, mjml version 4.0.0)
Preview panel is empty
Expected behavior:

I want to visualize my project.

MJML version:

Mac App - 2.8.0
MJML - 4.0.0
![capture d ecran 2018-03-06 a 13 39 20](https://user-images.githubusercontent.com/22197956/37051286-fdd51316-2143-11e8-8461-f50c5d3198c7.png)

**Comment by gnegreiros** [comment]
Export to HTML doesn't work either.

**Comment by meriadec** [comment]
Not sure I can help with so little information 😄 

- Does your code works in the MJML try-it-live? https://mjml.io/try-it-live
- Did you tried with a more simpler template (like the default ones suggested by the app when creating a new project)?
- Have you tested removing parts of your code to see what's causing the issue?

**Comment by gnegreiros** [comment]
Yes, I have made many emails templates before and this it's only a version from another old one.
This happening after I upgrade to 2.8 version.
I also tested on try-it-live and it's OK.

![capture d ecran 2018-03-06 a 14 41 08](https://user-images.githubusercontent.com/22197956/37054425-d4d28512-214c-11e8-8ace-5e2fe36f6ea4.png)

**Comment by meriadec** [comment]
Can you send me the mjml code causing the problem?
You can paste it directly here or reach me on the [MJML Slack](https://slacking-inviter.herokuapp.com/).

**Comment by gnegreiros** [comment]
Hi, It isn't the only that preview doesn't work, the old one's preview is not showing.
There is the code.
=====
<mjml>
  <mj-head>
    <mj-title>Setup Your Account</mj-title>
    <mj-attributes>

      <mj-all padding="0" />
      <mj-text font-family="Lato,sans-serif" font-weight="400" font-size="16px" line-height="1.5" color="#666666" />

      <mj-list font-family="Lato,sans-serif" font-weight="400" font-size="16px" line-height="1.8" color="#666666" padding="0" />

      <mj-button font-family="Lato, sans-serif" font-family="Lato" font-size="26" background-color="#217497" color="white" border-radius="3px" padding="10px" inner-padding="20 30" />

      <mj-class name="H1" font-family="Lato,sans-serif" font-weight="300" font-size="50px" line-height="1.2" color="#ffffff" align="center" />

      <mj-class name="H2" font-family="Lato,sans-serif" font-weight="400" font-size="30px" line-height="1.3" color="#666666" align="left" />

      <mj-class name="H3" font-family="Lato,sans-serif" font-weight="300" font-size="20px" line-height="1" color="#666666" padding="0 0 10 0" />

      <mj-class name="georgia" font-family="Georgia, serif" font-style="italic" font-size="40px" line-height="1" />

      <mj-class name="slogan" font-family="Lato,sans-serif" font-weight="400" font-size="16px" padding-top="15" />

      <mj-class name="link" font-family="Lato,sans-serif" font-weight="400" text-decoration="underline" color="blue" />

      <mj-class name="titre-article" font-family="Lato,sans-serif" font-weight="400" font-size="14px" align="left" padding="10" />

      <mj-class name="texte-article" font-family="Lato,sans-serif" font-weight="400" font-size="12px" align="left" padding="0 10" />

      <mj-class name="detail" font-family="Lato,sans-serif" font-weight="100" font-size="12px" />

      <mj-class name="city" padding="20 0 0 0" />

      <mj-class name="location" padding="0 10 0 0" />

      <mj-class name="disclaimer" color="#999999" />

      <mj-class name="center" align="center" />

      <mj-class name="couleur-cta" color="#217497" />

      <mj-class name="dark" color="#434343" />

      <mj-class name="light-grey" color="#F3F3F3" />

      <mj-class name="mid-grey" color="#DFDFDF" />

      <mj-class name="useful-link" color="#15c7a3" />

      <mj-class name="table-title" background-color="#999999" text-align="center" color="#ffffff" padding="30 0" />

      <mj-class name="table-content" background-color="#f3f3f3" padding="30 20" border-bottom="solid 1px #ffffff" />

    </mj-attributes>

    <mj-font href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel="stylesheet"></mj-font>

    <mj-style inline="inline">
      .link-style { font-size: 18px; color: #217497; line-height: 2; }

    </mj-style>
  </mj-head>
  <mj-body>
    <mj-container width="600px" background-color="#ffffff">

      

      <mj-section padding="20 0" full-width="full-width" padding="10 10 10 10" background-color="#2b2b2b">
        <mj-group>
          <mj-column width="15%">
            <mj-image width="50" align="left" padding-left="10" src="https://gallery.mailchimp.com/0fe3f872988daa5a866371d0b/images/098ffa9f-dcdd-4876-96eb-3a079038c5b5.png" href="http://canadel.com" />
          </mj-column>

          <mj-column width="70%" vertical-align="middle">
            <mj-text font-family="Lato,sans-serif" font-weight="100" font-size="30px" line-height="1" color="#ffffff" align="center" padding="10">
              Canadel Account
            </mj-text>
          </mj-column>
          <mj-column width="15%">

          </mj-column>
        </mj-group>
      </mj-section>

      

      <mj-section>
        <mj-column>
          <mj-spacer height="30px" />
        </mj-column>
      </mj-section>

      

      <mj-section mj-class="table-title">
        <mj-column>
          <mj-text mj-class="H1">
            Welcome to Canadel <br>{{Fname}}
          </mj-text>
        </mj-column>
      </mj-section>

      

      <mj-section mj-class="table-content">
        <mj-column>
          <mj-text mj-class="H2 " padding-bottom="20">
            Thank you for signing up for Canadel.
          </mj-text>
          <mj-text mj-class="">
            You just need to setup your password to start enjoying all the functionalities of our applications.
          </mj-text>
        </mj-column>
      </mj-section>

      

      <mj-section mj-class="table-content">
        <mj-column>
          <mj-button href="https://canadel.com">
            Create password
            </mj-buttom>
        </mj-column>
      </mj-section>

      

      <mj-section mj-class="table-content">
        <mj-column>
          <mj-text padding-bottom="20">
            For your reference, your username is <strong>{{username}}</strong> for logging in.
          </mj-text>
          <mj-text>
            Thanks,</br>
            Canadel Team
          </mj-text>
        </mj-column>
      </mj-section>

      

      <mj-section>
        <mj-column>
          <mj-spacer height="30px" />
        </mj-column>
      </mj-section>

      

      <mj-section padding="40 0" full-width="full-width" background-color="#2B2B2B">
        <mj-group>
          <mj-column width="55%">
            <mj-image width="50" align="left" padding-left="10" src="https://gallery.mailchimp.com/0fe3f872988daa5a866371d0b/images/098ffa9f-dcdd-4876-96eb-3a079038c5b5.png" href="http://canadel.com" />
          </mj-column>

          <mj-column width="15%">
            <mj-image width="32" padding-top="10px" href="https://www.facebook.com/canadelfurniture/" src="https://gallery.mailchimp.com/0fe3f872988daa5a866371d0b/images/a627ac09-1a72-4eae-ade2-344aa84181a6.png" />
          </mj-column>
          <mj-column width="15%">
            <mj-image width="32" padding-top="10px" href="https://www.pinterest.com/canadel/" src="https://gallery.mailchimp.com/0fe3f872988daa5a866371d0b/images/c8cafc6e-b562-4393-a02f-0b6cb1313bcb.png" />
          </mj-column>
          <mj-column width="15%">
            <mj-image width="32" padding-top="10px" href="https://www.houzz.com/pro/canadelfurniture/" src="https://gallery.mailchimp.com/0fe3f872988daa5a866371d0b/images/2ebcf4bc-1220-4b09-a092-05ee9685d3e1.png" />
          </mj-column>

          </mj-column>
        </mj-group>
      </mj-section>

      <mj-section padding="0 0 60 0" full-width="full-width" background-color="#2B2B2B">
        <mj-column>
          <mj-text mj-class="center" font-size="12">
            Canadel inc.</br>
            700 Canadel avenue, Louiseville (Quebec)</br>
            J5V 2L6 Canada
          </mj-text>
        </mj-column>
      </mj-section>

    </mj-container>
  </mj-body>
</mjml>

**Comment by meriadec** [comment]
Here is what I got from the developper console (View > Toggle Developer Tools)

```
MJML v3 syntax detected, migrating to MJML v4 syntax. Use mjml -m to get the migrated MJML.
Ignoring unsupported tag : mj-list on line 9
```

**Comment by gnegreiros** [comment]
Sorry, how do I do this?

**Comment by meriadec** [comment]
At line 9 of your mjml file, there is an `<mj-list>` tag, which is not supported anymore by mjml 4.
You can have your template back to work by removing that tag.

To replace the `<mj-list>` you can use `<mj-text>`  or `<mj-raw>` with regular HTML list tags.
You can find more information on the [documentation](https://mjml.io/documentation/).

**Comment by gnegreiros** [comment]
Ah, ok.
Thank you so much.
