### ISSUE TITLE
mj-social not responding to inner-padding

### ISSUE THREAD

**Issue by timschaaf** [mjmlio/mjml-app#217]
` <mj-section>
      <mj-column>
      	<mj-social align="right" font-size="12px" icon-size="28px" mode="horizontal" inner-padding="20px" >
          <mj-social-element href="#" icon-color="#4d4d4d" name="twitter" />
          <mj-social-element href="#" icon-color="#4d4d4d" name="facebook" />
          <mj-social-element href="#" icon-color="#4d4d4d" name ="linkedin" />
        </mj-social>
      </mj-column>
    </mj-section>`

Changes to inner-padding do not result in any changes in padding, within MJML App 2.8 or with HTML output from MJML app.

**Comment by timschaaf** [comment]
looks like padding on mj-social-element works so inner-padding is just not inherited properly

**Comment by meriadec** [comment]
Hey, for mjml related questions, please open issue directly on [mjml repository](https://github.com/mjmlio/mjml)
