### ISSUE TITLE
Editing the name of a template

### ISSUE THREAD

**Issue by ngarnier** [mjmlio/mjml-app#22]
In my templates, when hovering an existing template, the action to rename a template is not obvious.

 - [ ] What do you think about moving the input to the title of the template? 

![Illustration](https://cloud.githubusercontent.com/assets/4700883/14459649/71dbb0b0-00b9-11e6-8243-eaaf67f102af.png)

- [x] Maybe the icon could be more explicit too?

**Comment by GuillaumeBadi** [comment]
The edition mode is actually more dificult that it sounds on the paper, i didnt realized that Oo

**Comment by meriadec** [comment]
I'm on it.

**Comment by meriadec** [comment]
done. see https://github.com/mjmlio/mjml-app/pull/26

**Comment by GuillaumeBadi** [comment]
I think he was thinking about that: when the user clicks on the name, the name becomes an input

**Comment by GuillaumeBadi** [comment]
I am on it

**Comment by GuillaumeBadi** [comment]
done
