### ISSUE TITLE
Looking for Editor Shortcuts

### ISSUE THREAD

**Issue by hansnolte** [mjmlio/mjml-app#221]
Except for Ctrl+F and Ctrl+Shift+R I haven't found anything yet.
What about Block(Tag) operations, Multiple Selections etc?

Looking forward to every tip
Hans

**Comment by meriadec** [comment]
Hi, mjml-app use CodeMirror for text-edition. You can find a list of available commands here: https://codemirror.net/doc/manual.html#commands

**Comment by hansnolte** [comment]
Many thanks meriadec !
