### ISSUE TITLE
Two (or more) colums section no longer working with 2.8.0

### ISSUE THREAD

**Issue by evforija** [mjmlio/mjml-app#222]
Hi there, just updated to the new MJML version and all my emails broke. I frequently use the two column layout from here: https://mjml.io/documentation/#2-columns-section

and now it looks like this: 

![4front march 1-desktop](https://user-images.githubusercontent.com/32684477/37103195-a7f5bd7e-21f7-11e8-9c27-2c90c87a582a.png)

**Comment by evforija** [comment]
`

      
      <mj-section background-color="#fafafa" padding-bottom="20" padding-top="0">
        
        <mj-column>
          <mj-image width="50" src="https://autobooks.co/images/icons/invoice_envelope_acme.png" />

          <mj-text font-size="20" font-family="Helvetica Neue" font-weight="400" color="#626262" align="center">
            Online Invoices </mj-text>

          <mj-text color="#525252" font-family="Helvetica Neue" font-weight="300" font-size="12pt" align="center">
            Create and send invoices to your customers online. It's easy to view and manage their invoice history.
          </mj-text>
        </mj-column>

        
        <mj-column>
          <mj-image width="50" src="https://autobooks.co/images/icons/payment-options-acme.png" />
          <mj-text font-size="20" font-family="Helvetica Neue" color="#626262" font-weight="400" align="center">
            Payment Notifications </mj-text>

          <mj-text color="#525252" font-family="Helvetica Neue" font-size="12pt" font-weight="300" align="center">
            You can receive email notifications when your customers view and pay your invoices, instantly.

          </mj-text>

        </mj-column>
      </mj-section>
`

**Comment by meriadec** [comment]
Hello @evforija , it sounds like a MJML issue, rather than mjml app. Can you report it on the mjml repo? https://github.com/mjmlio/mjml

**Comment by meriadec** [comment]
You can find older mjml-app versions here: https://github.com/mjmlio/mjml-app/releases
