### ISSUE TITLE
Add a migrate to MJML4 syntax button

### ISSUE THREAD

**Issue by iRyusa** [mjmlio/mjml-app#224]
MJML4 has a built-in migration tool for older template in MJML3. 

In the app (and mjml-core) it migrates files on the fly, we might need to add a migration button when MJML3 syntax is detected.

**Comment by meriadec** [comment]
What should we use to migrate old code to new code? is there a method exported by mjml for that?

**Comment by ngarnier** [comment]
ye: https://github.com/mjmlio/mjml/tree/master/packages/mjml-migrate

**Comment by dshastry** [comment]
Maybe related so thought I'd add here. Getting the following error with old MJML 3.0 templates

![image](https://user-images.githubusercontent.com/4194561/37800222-2391ba4c-2df0-11e8-88fe-0c9ae2b2c5bc.png)

**Comment by dshastry** [comment]
No issues on previous versions of MJML app. latest version breaks and does not render any old templates.

**Comment by ngarnier** [comment]
@dshastry, the templates are automatically migrated so your migration fails here. You have an empty `mj-section` after the `<mjml>...</mjml>` tags which is invalid. Would remove them fix the issue?

If the issue persits, please open a separate issue and paste your MJML content that fails to render (this issue is for the feature tracking).

**Comment by dshastry** [comment]
@ngarnier, it does not fix the issue. the mj include seems to be failing. I removed everything and just kept one include inside mj body and still nothing. The individual mjml files render but if i call them in via include it fails. I'll create a separate issue and roll back to previous version for now.

**Comment by meriadec** [comment]
@iRyusa see commit above :arrow_up: 

in your opinion, what would be the best way to detect old mjml syntax? actually it shows the warning only [if mj-container is present](https://github.com/mjmlio/mjml-app/blob/master/src/helpers/detectOldMJMLSyntax.js) :joy: .

Also, it seems that migrating multiple times is not idempotent and can lead to weird results (3 clicks here):

![mjml](https://user-images.githubusercontent.com/315259/37879327-755fa54e-3077-11e8-8b24-d2d6d0ce2bb3.gif)

**Comment by kmcb777** [comment]
Above commit fixes the multiple migrates problem :
Since `isOldSyntaxDetected` is not refreshed when editor content changes, after migrating it is now manually set to `false`, assuming that we migrated successfully

**Comment by NorthstarTech** [comment]
@meriadec Can you please let me know how can you get the button of migrate to migrate mjml3 to mjml4. Help Needed.

Link: (https://user-images.githubusercontent.com/315259/37879327-755fa54e-3077-11e8-8b24-d2d6d0ce2bb3.gif)

**Comment by kmcb777** [comment]
@NorthstarTech it should display when you open a mjml file that contains a `mj-container`
