### ISSUE TITLE
Cannot open any projects or create new files

### ISSUE THREAD

**Issue by OliverPWilson** [mjmlio/mjml-app#225]
Hi

Just downloaded MJML-app and created a project. The project files are created in Finder, but opening the project in the app does not load the text editor, the file view, or the render preview. Clicking 'new file' produces the error "Error creating file" with no error code or any other information:

![screen shot 2018-03-19 at 17 01 35](https://user-images.githubusercontent.com/9893763/37610347-3f0b6c60-2b97-11e8-9f3d-5fab2bfb1a36.png)

Uninstalling and reinstalling doesn't work, neither does opening files from Finder. 

I'm on Mac OS High Sierra 10.13.3

MGML app v^2.8.0
MJML v^4.0.0

Thanks

**Comment by meriadec** [comment]
Hey @OliverPWilson , can you click on Windows > Open dev tools, then screenshot the error? Thanks!

**Comment by meriadec** [comment]
Looks similar to https://github.com/mjmlio/mjml-app/issues/121 as I see in your screenshot that you are using Dropbox also

**Comment by OliverPWilson** [comment]
Not able to send the screenshot as it's a work dropbox environment but I think I have figured out the problem - the file location string contains the character "&" which seems to prematurely end the string for react.js

Will transfer project to desktop and see if it works there.

**Comment by meriadec** [comment]
still an issue?

**Comment by OliverPWilson** [comment]
Sorry - the solution is to not create project folders nested inside a folder with the character "&" in the name. Weird but easy fix.
