### ISSUE TITLE
Upgrade to MJML 4.0.2

### ISSUE THREAD

**Issue by rinopo** [mjmlio/mjml-app#229]
Hi,
Thank you so much for the MJML App!

MJML 4.0.2 includes some significant fixes and improvements.
https://github.com/mjmlio/mjml/releases/tag/v4.0.2

Since the custom MJML feature is still not working for the OSX version (#187), could you please upgrade the embeded MJML to 4.0.2 ?

**Comment by meriadec** [comment]
I just updated it, it will be shipped in next release. You can build your own version following the instructions in the [README](https://github.com/mjmlio/mjml-app/blob/master/README.md).

**Comment by rinopo** [comment]
@meriadec 
Thanks a lot!
