### ISSUE TITLE
Sending a test email: provide users with more information

### ISSUE THREAD

**Issue by ngarnier** [mjmlio/mjml-app#23]
Sending a test email doesn't feel obvious for users who are not familiar with Mailjet.

It'd be great to add: 
 - [x] under Mailjet API Key: 
   - "You can find your API Keys in the [Account/API Key section](https://app.mailjet.com/account/api_keys)"
 - [x] under From email: 
   - "The from email must be a [verified sender](https://app.mailjet.com/account/sender)"

If there is an issue with the sending of the email, the app shows "Not sent!". It'd be great to give more information, such as: 
 - [x] invalid API Keys
 - [x] invalid sender address
 - [x] invalid recipient address

**Comment by GuillaumeBadi** [comment]
:+1:

**Comment by GuillaumeBadi** [comment]
Pull request almost ready!

**Comment by divyeshmakwana96** [comment]
@ngarnier I created a cli utility which works with MJML https://github.com/divyeshmakwana96/Pochta

**Comment by ngarnier** [comment]
@divyeshmakwana96 wow, looks really nice! I need to give it a try
