### ISSUE TITLE
Using "mj-table" results in "[object Object]" in table attributes.

### ISSUE THREAD

**Issue by warrickbayman** [mjmlio/mjml-app#231]
Hi.

I'm using the mj-table component like this:

```html
<mj-table color="#888888">
```

And I'm getting this result:

```html
<table 0="[object Object]" 1="[object Object]" 2="[object Object]" border="0" style="cellspacing:0;color:#888888;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:22px;table-layout:auto;width:100%;">
```

Without the "color" attribute on the `mj-table` element, the `0`, `1` and `2` attributes on the resulting "table" disappear.

**Comment by iRyusa** [comment]
Hi @warrickbayman and thanks for finding this !

This is related to MJML so can you open it back on the MJML Repo instead of MJML-APP ? Thanks !

**Comment by warrickbayman** [comment]
@iRyusa will do.
