### ISSUE TITLE
owa="desktop" not working

### ISSUE THREAD

**Issue by simonkrabbe** [mjmlio/mjml-app#234]
Applying owa="desktop" to the <mjml> tag breaks the template.

**Comment by iRyusa** [comment]
Did you tried with version 2.9 ?

**Comment by simonkrabbe** [comment]
Yep, I'm on 2.9

**Comment by kmcb777** [comment]
@simonkrabbe Hi, thanks for reporting this, i thought we had already fixed it, until the next release a workaround would be to add
`<mjml></mjml>` before your template
