### ISSUE TITLE
Switch to 3.3 engine

### ISSUE THREAD

**Issue by lucasnantonio** [mjmlio/mjml-app#236]
Hey guys, the migrate button is not working 100% for us. Is there any way we can switch the engine back to 3.3 so we can continue developing with the editor?

I don't understand how to use the custom engine input on the settings tab

![image](https://user-images.githubusercontent.com/13240286/38582191-5f64047c-3ce5-11e8-823c-4e19d0161d0c.png)

**Comment by meriadec** [comment]
You have multiple solutions:

- Download an older version from the [releases page](https://github.com/mjmlio/mjml-app/releases)
- Install [`mjml-cli`](https://www.npmjs.com/package/mjml-cli) and put its path in the custom MJML setting.
- Install development version of the app, change mjml version, and re-build your own app.
