### ISSUE TITLE
MJML Desktop App opens blank window

### ISSUE THREAD

**Issue by shelby2245** [mjmlio/mjml-app#242]
Every time I try to open the MJML desktop app it's completely blank (screenshot below), I can't even open existing project. It started happening with version 2.6, so I updated to 2.9, but its still happening. I've tried deleting and reinstalling the app and even tried a registry cleanup. It's still opening a blank screen.

I love this app and rely on it heavily for my marketing business. Please help!

![mjml](https://user-images.githubusercontent.com/38889779/39483950-e7978aaa-4d28-11e8-9bf4-0733eea6b914.PNG)

**Comment by meriadec** [comment]
Hi @shelby2245, sorry for your problem !

Apparently there is some project or some setting that make your app crash. You can clean the app settings (and projects list) by deleting the folder located here (on Windows):

```
C:\Users\<you>\AppData\Local\Programs\mjml-app
```

(you will not lose your projects)

Then reinstall the app. And pray.

**Comment by shelby2245** [comment]
Hi Meriadec,

It looks like that didn't work. Any other suggestions?

**Comment by meriadec** [comment]
Can you open the dev tools by clicking on Window > Open dev tools, then copy paste the error stack trace ?

**Comment by shelby2245** [comment]
It looks like that option doesn't exist and and when I try to click on any
of the other functions in that window it doesn't do anything.

**Comment by shelby2245** [comment]
So I found an option for Toggle Dev Tools under View and it shows this error in the console:

"Uncaught (in promise) Error: EINVAL: invalid argument, stat"

and then gives the location of one of my MJML templates.

**Comment by meriadec** [comment]
Sounds like something is broken with one of your template, maybe permissions? Dunno. What I can advise you is either delete the settings file of the app, either move/delete your problematic project folder.

**Comment by shelby2245** [comment]
It does it will all of my files. It’s like my computer no longer recognizes this kind of file type.

 

Best,

Shelby

**Comment by shelby2245** [comment]
UPDATE: I found a file in AppData/Roaming which seems to have been causing the issue. I'm able to open the app and create new files now, but I still cannot open saved projects. Seems my computer cannot find the program use to open the saved MJML files and I cannot find the app in Program files.
