### ISSUE TITLE
Open current folder when exporting as Html not project root

### ISSUE THREAD

**Issue by eikaramba** [mjmlio/mjml-app#244]
If i have the project root under /example/ but within the project open files from /example/partner/, whenever i then export the file as Html, the project root folder is opened. It would be great if the actual folder would be opened of the source file i'm editing.

**Comment by meriadec** [comment]
Hi, good idea :+1: 
The code is here: https://github.com/mjmlio/mjml-app/blob/bb3b913fb5aa66301eb8e516d51a19a76e031095/src/pages/Project/index.js#L127-L131

Feel free to make a PR.
