### ISSUE TITLE
Included Files that contain mj-head produce white screen

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#251]
In my index.mjml file I have a structure as below (edit: github is not formatting correctly so attached as file).

This is how my first include, header.mjml is structured ::
```
<mjml>
<mj-head>
    <mj-include path="../../Styles/dpg-style.mjml.css" />
  </mj-head>
<mj-body background-color="#eaeaea">
    <mj-section background-color="none">
    </mj-section>
      <!--Email Header-->
      <mj-section border-bottom="1px solid #eaeaea" padding="0" background-color="white">
        <mj-text>
          <div style="padding-left:25px; padding-right:25px; padding-top:15px;" class="email-header">
            <a class="logo" href="http://www.debtpaygateway.com" style="float:left; margin-bottom:10px;"><img src="https://dpp-publicassets.s3.amazonaws.com/dpg/email/tradeshow/dpg-header-logo.png" width="120px"/></a>
            <p style="float:right; color:#999; text-transform:uppercase; font-size:11px;">Account Notification • {MONTH},{YEAR}</p>
          </div>
        </mj-text>
      </mj-section>
  </mj-body>
</mjml>

```

The issue is that index.mjml will not generate if <mj-head> exists in the included file. Removing mj-head in any included files renders the template correctly. The presence of the CSS file is irrelevant. index.mjml generates correctly if css file is present or not in the includes. Only fails if mj-head is present.

This was not an issue in previous versions of MJML only with MJML 4 app. All these templates were previously built and used with MJML 3 and it worked fine.

**Comment by dshastry** [comment]
[index.txt](https://github.com/mjmlio/mjml-app/files/2064299/index.txt)

**Comment by iRyusa** [comment]
Hi can you check this has been fixed ? I believe this was an issue in the very first version of MJML App with MJML4

**Comment by dshastry** [comment]
Hi guys, I will confirm this week and report back. Thank you for circling back around to this.
