### ISSUE TITLE
Highlight Blocks in Preview Window on Mouseover Code

### ISSUE THREAD

**Issue by bkonia** [mjmlio/mjml-app#252]
It would be great if the MJML app worked like how Developer Tools works in any modern browser. When you mouseover or click on a code block, it would highlight the corresponding section in the preview window. This would make it much easier to find the code you need to edit for a particular section.

**Comment by iRyusa** [comment]
Well, It could be done with css-class but it would be really hard to do. If someone willing to do it feel free but for now that's not MJML App roadmap
