### ISSUE TITLE
Interface issue

### ISSUE THREAD

**Issue by GrzegorzCupial** [mjmlio/mjml-app#257]
Hi,
sometimes im facing with some issues while opening mjml app. As u can see on photo below, im not able to see anything but i can interact with app elements. I can copy code, and click buttons that i cant actually see :)
![captured](https://user-images.githubusercontent.com/20965336/42656596-07dcde48-8620-11e8-846b-74a960c3f99c.png)

**Comment by meriadec** [comment]
How to reproduce? Do you have errors in console? (Window > Show Dev tools) Do you reproduce on another computer? On another template?

**Comment by GrzegorzCupial** [comment]
Hi,
I have resolved this issue using View -> Reload.
I dont have any errors in console and this issue appears on every templates.

**Comment by iRyusa** [comment]
If you open the dev console (in Window > Show dev tool as mentioned by Meri), do you have any error ?

It looks like an issue with your settings file, may be try to remove / back-up it to see if it works without it
