### ISSUE TITLE
mj-hero validation errors in editor

### ISSUE THREAD

**Issue by dpHARDIN** [mjmlio/mjml-app#259]
Commented code placed within mj-hero tags errors as mj-raw.

Code from mj-hero documentation screenshot
![screen shot 2018-08-15 at 9 23 54 am](https://user-images.githubusercontent.com/35699907/44153151-06b58c4c-a06d-11e8-9410-85c77303b8dc.png)

Comments outside tag validate fine.
Width attribute in mj-hero also failing (first red x in screen shot)

**Comment by kmcb777** [comment]
hi @dpHARDIN thanks for reporting this !
This issue is actually mjml's fault, not the app's, so i'll close it
The fix will be included in the next release 👍
