### ISSUE TITLE
File names truncated in panel is:request

### ISSUE THREAD

**Issue by dpHARDIN** [mjmlio/mjml-app#261]
Feature Request

Can the left panel (file panel) be more flexible in sizing? The current limit is too short for my needs. It may also be an accessibility issue?

**Comment by meriadec** [comment]
Files list panel maximum size is defined here : https://github.com/mjmlio/mjml-app/blob/6f6fc3o82795e6c3c7c8fc5297bef018f7bb7707d/src/components/FilesList/index.js#L277

You can either increase or remove the prop (removing it ends on no maximum value: let's use that!).

Would you mind make a PR? Thx.

**Comment by kmcb777** [comment]
@dpHARDIN I made a PR that changes the panel maxSize from 250 to 350, will it be enough ?
