### ISSUE TITLE
Needs explicit Save function

### ISSUE THREAD

**Issue by aaron-harding** [mjmlio/mjml-app#263]
I have been working on a few templates that are within the same folder. I opened the App and it must've glitched out because it's removed all of my MJML in one layout and replaced it with the contents of another email, so I have lost a mornings work!

This would not have happened if you had to save the file. Because it's a live update, it's replaced the contents and I didn't have a say in whether it should save or not.

Not sure if the bug is replicatable since all I did was open the app.

**Comment by iRyusa** [comment]
Well, it's really weird that you're the first user to have this behavior. Are you sure you don't use something like dropbox/drive or something that would synchronise the folder of your project ?

**Comment by aaron-harding** [comment]
iRyusa, nothing like that. It's not linked to anything, just a regular install and using a folder as a project.

**Comment by meriadec** [comment]
relatable: https://github.com/mjmlio/mjml-app/issues/219
