### ISSUE TITLE
Can't export a project multiple times 

### ISSUE THREAD

**Issue by ParallelUniv3rse** [mjmlio/mjml-app#268]
**Describe the bug**
Exporting a project works normally the first time I export one, trying to export again just silently fails and the folder selection window does not even show up.

**To Reproduce**
1. Export a project
2. Save the files
3. Try to export again
4. The bottom select/export menu just slides down and nothing happens

**Expected behavior**
I am able to export a project without having to restart the application.

**Environment (please complete the following information):**
 - OS: MacOS High Sierra and Mojave; latest versions
 - App Version 2.10.0

**Comment by iRyusa** [comment]
Looks like this has been merged ? I can close
