### ISSUE TITLE
Resizing MJML App

### ISSUE THREAD

**Issue by ngarnier** [mjmlio/mjml-app#27]
It seems a bug prevents users from resizing the app. 

- If I click in the top-right or top-left corner, the top of the app just jumps to the top of my screen and I can't see anymore the top bar of the app. 

- If I click on the bottom-right or bottom-left corner, the bottom of the app jumps to the bottom of my screen.

- If I toggle full screen mode, it's really hard to make the top bar appear again to exit full screen mode.
![9glsk5el44](https://cloud.githubusercontent.com/assets/4700883/14600071/37a7a0a6-055b-11e6-9d2d-af87f32e1c05.gif)

Thanks!

**Comment by GuillaumeBadi** [comment]
done: https://github.com/mjmlio/mjml-app/commit/b526b7dc4333059159fbb558243c9cae7b5b207a
