### ISSUE TITLE
Why doesn't the MJML app use the latest version of MJML?

### ISSUE THREAD

**Issue by matthewahillman** [mjmlio/mjml-app#275]
As the title says, why doesn't the MJML app use the latest version of MJML? Currently my app is using 4.1.2, anything I do to try and point it to a custom engine doesn't work. But the app should really auto update to using the current latest version of MJML, much like browsers etc do and other programs do with updates like Atom.

**Comment by medarob** [comment]
That would be good! I wonder myself why the App is not up-to-date...

**Comment by vicmunez85** [comment]
Ditto, This would be amazing. I see releases with new features but no updates to the app :(

**Comment by ngarnier** [comment]
Indeed, the update of MJML version is not automatic so we have to do it manually. Feel free to contribute by updating the version, building it and making a PR :).

**Comment by keberox** [comment]
Since the app is using Electron, I believe this should not be difficult to accomplish - having the app use the latest version of the MJML engine.

**Comment by kmcb777** [comment]
Hi @matthewahillman @medarob @vicmunez85 @keberox , a new app release is available with mjml4.3.1, feel free to try it out !
