### ISSUE TITLE
mjml-app hot reload custom component

### ISSUE THREAD

**Issue by dschach1** [mjmlio/mjml-app#279]
mjml-app loads custom components specific in the .mjmlconfig file.  However, it does not reload them when the source of the custom component changes. Electron hot reloads its own source when making edits.  It's tedious to develop a new custom component because I'm constantly restarting mjml-app. Am I missing something simple here?

**Describe the solution you'd like**
A way to hot load a custom component

**Comment by iRyusa** [comment]
I don't think we'll be able to provide this feature, MJML isn't an IDE for developing custom components. I 'm closing this one.
