### ISSUE TITLE
Fix the position of error alert

### ISSUE THREAD

**Issue by robsonsobral** [mjmlio/mjml-app#28]
Hi!

I'm testing the app and I was getting an error I couldn't see it.

    Cannot read property 'defaultMJMLDefinition' of undefined

I had scrolled the preview to the bottom, but the error alert was at the top of it. Is it possible to position the error alert on the top relatively to the screen? Something like `position: fixed; top: 0;`?

Thanks!

**Comment by meriadec** [comment]
Hi, thanks for the input. It seems that you have written a tag which is not listed as an mjml component. If you are trying to write a `p` tag (for example), make sur it is wrapped in an `mj-text`.

It's true that the error notification and message could me more clear and user friendly :p We could improve that later.

Let us know if it fixed the problem!

**Comment by GuillaumeBadi** [comment]
The mjml team is working on better error messages for a future release as well, so we are waiting for that

**Comment by robsonsobral** [comment]
I agree, but the issue I'm worried about right now it's just the position. After some coding, I need to scroll the preview to see what I'm doing and I lost the error message. I think they should be always visible.

To make it `fixed` is enough for now, just because it's really annoying to wait for nothing to happen and then scroll the preview back to the top and find an error. But some kind of console error message would be awesome!

**Comment by GuillaumeBadi** [comment]
Yep ! you're right. I'll change that later today! 👍

**Comment by meriadec** [comment]
The pb is that it's already in position fixed (see [here](https://github.com/mjmlio/mjml-app/blob/master/src/helpers/error.js)) so i guess we need to pop it out of the iframe source code :p
