### ISSUE TITLE
Remove padding from sections

### ISSUE THREAD

**Issue by epeck-graphicproducts** [mjmlio/mjml-app#283]
So I'm working on creating some transaction emails and I'm new to mjml and struggling with some basics.

I can't seem to figure out how to get rid of all of the extra space in between my sections:
![image](https://user-images.githubusercontent.com/49292317/55591302-0a7fe280-56ea-11e9-86e9-38e4db555d5a.png)

*I also can't seem to figure out how to get the word 'QTY' to stop word breaking....

Any feedback and suggestions would be super appreciated. Thanks!

Index Code:
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-text align="left" font-family="sans-serif" color="#000" font-size="16px" line-height="24px" />
      <mj-section background-color="#fff" />
      <mj-button background-color="#F45E43" color="#fff" font-size="14px" /> </mj-attributes>
  </mj-head>
  <mj-body background-color="#eee">
    <mj-section>
      <mj-column>
        <mj-text>
          <h1 style="color:#033047;font-size:18px;">ORDER CONFIRMATION</h1>
          <mj-text>Customer #:<br> Order #: ((OrderNbr))<br> Order Status: ((poorderslist.Status))<br> Ship-to Name: ((poreceiptslist.ShipToLocationID.DefContactID.FirstName)) ((poreceiptslist.ShipToLocationID.DefContactID.LastName)) <br> Ship-to Company: ((poreceiptslist.ShipToLocationID.Descr))<br>            Shipping Location: ((poreceiptslist.ShipToLocationID))<br> Order Date: ((poorderslist.CreatedDateTime))​<br> Customer PO#: <br> Terms: ((poorderslist.TermsID))​<br> Ship Via:<br> FOB: ((poorderslist.FOBPoint.FOBPointID))​<br> Purchaser:<br>            Comment:<br> Territory: </mj-text>
      </mj-column>
    </mj-section>
    <mj-section>
      <mj-column>
        <mj-include path="./test.mjml" /> </mj-column>
    </mj-section>
    <mj-section>
      <mj-column>
        <mj-text> Payment Type:<br> Ship Weight:<br> Freight Amount:<br> Order Total (USD): ((poorderslist.OrderTotal))<br></br> Date and time of this email: 01/11/2019 11:01:07 AM Pacific<br> </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

Data Table Code:
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>
          <mj-style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    html,
    body,
    table,
    tbody,
    tr,
    td,
    div,
    p,
    ul,
    ol,
    li,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
      margin: 0;
      padding: 0;
    }
    body {
      margin: 0;
      padding: 0;
      font-size: 0;
      line-height: 0;
      -ms-text-size-adjust: 100%;
      -webkit-text-size-adjust: 100%;
    }
    table {
      border-spacing: 0;
      mso-table-lspace: 0pt;
      mso-table-rspace: 0pt;
    }
    table td {
      border-collapse: collapse;
    }
    .ExternalClass {
      width: 100%;
    }
    .ExternalClass,
    .ExternalClass p,
    .ExternalClass span,
    .ExternalClass font,
    .ExternalClass td,
    .ExternalClass div {
      line-height: 100%;
    }
    /* Outermost container in Outlook.com */
    .ReadMsgBody {
      width: 100%;
    }
    img {
      -ms-interpolation-mode: bicubic;
    }
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
      font-family: Arial;
    }
    h1 {
      font-size: 28px;
      line-height: 32px;
      padding-top: 10px;
      padding-bottom: 24px;
    }
    h2 {
      font-size: 24px;
      line-height: 28px;
      padding-top: 10px;
      padding-bottom: 20px;
    }
    h3 {
      font-size: 20px;
      line-height: 24px;
      padding-top: 10px;
      padding-bottom: 16px;
    }
    p {
      font-size: 16px;
      line-height: 20px;
      font-family: Georgia, Arial, sans-serif;
    }
    </style>

    <style>
      .container600 {
        width: 600px;
        max-width: 100%;
      }
    @media all and (max-width: 599px) {
      .container600 {
        width: 100% !important;
      }
      
    
      .smarttable {
        border: 0;
      }
      .smarttable thead {
        display:none;
        border: none;
        clip: rect(0 0 0 0);
        height: 0px;
        margin: 0px;
        overflow: hidden;
        padding: 0;
        max-width:0px;
        max-height:0px;
      }
      .smarttable tr {
        display: block;
        width:90%;
        margin:20px auto;
      }
      .smarttable td {
        border-bottom: 1px solid #000;
        display: block;
        font-size: 14px;
        text-align: right;
      }
      .smarttable td:before {
        content: attr(data-label);
        float: left;
        font-weight: bold;
        text-transform: uppercase;
      }
    }
  </style>
</mj-style>
   

</head>
    <center>

        

                <table width="100%" cellpadding="0" cellspacing="0" style="min-width:100%;">
 
                  <tr>
                    <td style="padding:5px;">

                        <table class="smarttable" width="100%" cellpadding="0" cellspacing="0" style="min-width:100%;">
                          <thead>
                            <tr>
                              <th scope="col" style="padding:5px; font-family: Arial,sans-serif; font-size: 14px; line-height:10px;line-height:15px;color:#033047;text-align:left;background-color:#eee">QTY</th>
                              <th scope="col" style="padding:5px; font-family: Arial,sans-serif; font-size: 14px; line-height:10px;line-height:15px;color:#033047;text-align:left;background-color:#eee">UM</th>
                              <th scope="col" style="padding:5px; font-family: Arial,sans-serif; font-size: 14px; line-height:10px;line-height:15px;color:#033047;text-align:left;background-color:#eee">ITEM #</th>
                                   <th scope="col" style="padding:5px; font-family: Arial,sans-serif; font-size: 14px; line-height:20px;line-height:30px;color:#033047;text-align:left;background-color:#eee">DESCRIPTION</th>
                                   <th scope="col" style="padding:5px; font-family: Arial,sans-serif; font-size: 14px; line-height:10px;line-height:15px;color:#033047;text-align:left;background-color:#eee">UNIT PRICE</th>
                                   <th scope="col" style="padding:5px; font-family: Arial,sans-serif; font-size: 14px; line-height:10px;line-height:15px;color:#033047;text-align:left;background-color:#eee">EXTENDED PRICE</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td data-label="QTY" valign="top" style="padding:5px; font-family: Arial,sans-serif; font-size: 12px; line-height:20px;">12</td>
                              <td data-label="UM" valign="top" style="padding:5px; font-family: Arial,sans-serif; font-size: 12px; line-height:20px;">200R</td>
                              <td data-label="ITEM #" valign="top" style="padding:5px; font-family: Arial,sans-serif; font-size: 12px; line-height:20px;">T0406-70</td>
                              <td data-label="DESCRIPTION" valign="top" style="padding:5px; font-family: Arial,sans-serif; font-size: 12px; line-height:20px;">	DLT 4x6 WARNING AF OUTDOOR</td>
                              <td data-label="UNIT PRICE" valign="top" style="padding:5px; font-family: Arial,sans-serif; font-size: 12px; line-height:20px;">$214.99</td>
                              <td data-label="EXTENDED PRICE" valign="top" style="padding:5px; font-family: Arial,sans-serif; font-size: 12px; line-height:20px;">$2,579.88</td>
                            </tr>

             
                          </tbody>
                        </table>

                    </td>
                  </tr>
                </table>

              </td>
        </tr>
    </table>

  
    </center>

        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

**Comment by meriadec** [comment]
not related to mjml-app, please open an issue on [the mjml repo](https://github.com/mjmlio/mjml)

**Comment by kmcb777** [comment]
or come to https://mjml.slack.com, best place to ask questions 👍

**Comment by epeck-graphicproducts** [comment]
My company has Slack blocked….
