### ISSUE TITLE
Parent Directory Doesn't Exist Error

### ISSUE THREAD

**Issue by AlyssaGodfrey** [mjmlio/mjml-app#284]
**Describe the bug**
When I try to create a new project, I get the error message "Parent directory doesn't exist" no matter where I try to save the project.

**To Reproduce**
1. Open MJML app and click create new project
2. Type a project name
3. Choose a folder

**Screenshots**
![image](https://user-images.githubusercontent.com/33841093/56139993-fb115c80-5f67-11e9-9bba-0cedcb5f5a7a.png)

**Environment (please complete the following information):**
 - OS: Windows
 - App Version: 4.3.1

**Comment by meriadec** [comment]
This is problematic, given the code the error can happen when either the destination parent folder can't be found, or can't be written, or the destination folder is not empty. I wonder if it's relatable to the way paths are handled on Windows.

To reproduce I have to setup a VM.

As a workaround, are you able to:
- create a folder on your disk, with `index.mjml`
- open as a project in mjml-app

**Comment by AlyssaGodfrey** [comment]
Hi, I'm so sorry I never responded. I was able to solve this by moving everything into a new folder on my desktop. I'm not sure what the issue was, but thank you for looking into it.

**Comment by meriadec** [comment]
Arf :) thanks for the follow up. so given your answer I suspect that the app were either not able to retrieve the folder (exotic characters in the full path?) or the destination directory was held by another process (so not writtable), as it's an usual problem on Windows. closing this one
