### ISSUE TITLE
Can't open files

### ISSUE THREAD

**Issue by robsonsobral** [mjmlio/mjml-app#29]
Hi!

I tried to open a file I created on a text editor and... Nothing happened!

I'm running Ubuntu16, but I tested on 15 also.

Thanks!

**Comment by meriadec** [comment]
Are you using the dev version or a release (1.1.1 I guess)?
Can you test with that file? I just tested with success on Arch Linux (should not be different from Ububuntu).

**Comment by meriadec** [comment]
I just generated the binary release for 1.1.2
you can [download it here and test again](https://github.com/mjmlio/mjml-app/releases/download/1.1.2/mjml-app-linux-x64.zip)

**Comment by robsonsobral** [comment]
Nopes! I click Open, I choose the file and... Nothing happens!

**Comment by GuillaumeBadi** [comment]
It works on my side too.. Can you try to run it in dev mode ?

**Comment by robsonsobral** [comment]
Idiot question, @GuillaumeBadi : how do I do that?

**Comment by GuillaumeBadi** [comment]
If you are not familiar with the Node.js environment, don't bother to install it. I will try today to reproduce the error, but I am not sure where to look, 
I'll keep you guys up to date

**Comment by meriadec** [comment]
Can you show the file you are trying to open? Because when you try to open a file which is not an mjml file, it does nothing.

**Comment by robsonsobral** [comment]
Wow! @meriadec is (almost) right! Almost because my file wasn't a _valid_ MJML file.

I tried using a new file and it opened. Them I tested the content of the previous file in a new one and found a "bug": a `table` HTML tag. Replacing the `table` by `mj-table` was enough to make the file "openable".

Maybe you need to think about a `window.alert` or something like that for these cases.

I'm so sorry, guys! Please, forgive me for give you all so much trouble.

Thank you for your help and patience.

**Comment by meriadec** [comment]
You're totally right, we definitely need to inform user when the opening fail :p 
It will be in the task list. Happy mailing!

**Comment by GuillaumeBadi** [comment]
Cool ! Glad it works for you!
