### ISSUE TITLE
php tags and preview

### ISSUE THREAD

**Issue by guidoferreyra** [mjmlio/mjml-app#291]
I want to use mjml combined with php tags that adds variable texts to the mail. At the moment the preview is removing the begining of the tag `<?=` and produce a strange preview.

**To Reproduce**
Add a php tag like `<?= $orderPage->givenName() ?>`

**Expected behavior**
Ignore this tags or maybe replace them with a small badge that indicates that is a variable text?

**Screenshots**

<img width="899" alt="Captura de pantalla 2019-07-11 a la(s) 14 08 59" src="https://user-images.githubusercontent.com/1755590/61070628-8b373480-a3e5-11e9-9b1f-dfa43a348ad0.png">

**Environment (please complete the following information):**
 - OS: OSX
 - App Version: 2.11.0

**Comment by kmcb777** [comment]
Hi @guidoferreyra, the preview is rendering the html like a browser, so this is interpreted as a html tag.
I'm afraid we can't do much about this. We can't escape the characters because real html can be used in a mj-text.
