### ISSUE TITLE
More often updates

### ISSUE THREAD

**Issue by Niputi** [mjmlio/mjml-app#301]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I can't install latest version of mjml with npm/yarn because of company restrictions

**Describe the solution you'd like**
mjml app getting updated to latest version when mjml is updated.

**Comment by ngarnier** [comment]
We're already doing our best to update the app as soon as possible, but thanks for your feedback. 

Help is also appreciated so feel free to contribute by doing PRs as the app is open source.
