### ISSUE TITLE
Questions on MJML features

### ISSUE THREAD

**Issue by connecteev** [mjmlio/mjml-app#304]
I haven't found answers to these, would love some thoughts on
1. How can you create an image with a link in MJML?
2. How can you style a text link?
3. Is there a way to set the base-url for an entire section / column / something else, like you can do for mj-navbar?
```
        <mj-navbar base-url="https://www.myURL.com" hamburger="hamburger" ico-color="#ffffff">
```

**Comment by ngarnier** [comment]
Hi, 

1. How can you create an image with a link in MJML? Use the `href` attribute of `mj-image` ([doc](https://mjml.io/documentation/#mjml-image))
2. How can you style a text link? Like you would do in HTML, simply use HTML inside `mj-text` ([doc](https://mjml.io/documentation/#mjml-text))
3. Is there a way to set the base-url for an entire section / column / something else, like you can do for mj-navbar? No

**Comment by connecteev** [comment]
@ngarnier thank you for the answers, this is very helpful.
WOuld it be possible to do # 3 above in the future?
Also, is there a collection of community-created MJML templates somewhere that I can look to for inspiration? THanks!

**Comment by ngarnier** [comment]
It is not planned to support links around a whole section as it causes a lot of issues in email clients.

You can find community templates on https://mjml.io/templates
