### ISSUE TITLE
Scrollable preview in project grid view

### ISSUE THREAD

**Issue by dakur** [mjmlio/mjml-app#307]
In project overview (grid of projects), it could be useful to be able to scroll through the previews so you do not have to open an e-mail to see the rest of its content. [Bee](https://beefree.io) actually has this functionality implemented if you want to see the idea working.

Screenshot from BeePro:  
![image](https://user-images.githubusercontent.com/9862581/70900088-61b7b000-1ff8-11ea-9e99-97736c368af2.png)

**Comment by iRyusa** [comment]
We could do that, but I think the perf won't be really good as it will require a lot of iframe... Maybe we can solve this by implementing a quick preview window?

**Comment by dakur** [comment]
> We could do that, but I think the perf won't be really good as it will require a lot of iframe... Maybe we can solve this by implementing a quick preview window?

Well, that's probably not so convenient because you have to do a lot of clicking until you know which e-mail is which. Probably better than current state, but still not ideal.

Can not be performance of originally suggested solution improved by caching a screenshot of each of the e-mail listed?

**Comment by iRyusa** [comment]
Then we need to need to do a full width screenshot of the email 🤔maybe it can be done we have to check how screenshot are handled in the app

**Comment by dakur** [comment]
> Then we need to need to do a full width screenshot of the email 🤔maybe it can be done we have to check how screenshot are handled in the app

Maybe screenshot could be made onclose by default and for these e-mails which do not have screenshot cached yet would be done imidiatelly when rendering grid view (there should be minimum of them).
