### ISSUE TITLE
Firefox on MacOs downloads the wrong application file

### ISSUE THREAD

**Issue by lemnis** [mjmlio/mjml-app#309]
1. Startup Firefox on Mac
2. Go to https://mjmlio.github.io/mjml-app/
3. Click on "Download for ..."
4. *.exe gets downloaded

User-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0"

**Comment by kmcb777** [comment]
Hi @lemnis thanks for reporting this, the links generation have now been updated. I just tried on osx/firefox and i properly get the .dmg 👍
