### ISSUE TITLE
Bug when closing the App (OSX) 

### ISSUE THREAD

**Issue by ngarnier** [mjmlio/mjml-app#31]
When you click on the red button to close the app, it will hide it as expected. Though, if you click again on the icon in the dock, the app doesn't show anymore and you have to quit it to be able to open it again.

![](http://g.recordit.co/bMzjF9jBsm.gif)

**Comment by meriadec** [comment]
I guess we could do a `app.quit()` [in main.js](https://github.com/mjmlio/mjml-app/blob/master/main.js#L44) :

```
  mainWindow.on('closed', () => {
    app.quit()
  })
```

What dyou think @GuillaumeBadi ?
