### ISSUE TITLE
Spelling...

### ISSUE THREAD

**Issue by saucytomato** [mjmlio/mjml-app#32]
<img width="276" alt="screen shot 2016-05-03 at 6 31 30 pm" src="https://cloud.githubusercontent.com/assets/7997954/15001454/3883a106-115d-11e6-885f-12b2463d65c5.png">
It should be updates, not upadates.

**Comment by meriadec** [comment]
already fixed [here](https://github.com/mjmlio/mjml-app/pull/30).

![notuhnt](https://cloud.githubusercontent.com/assets/315259/15007281/edd86fe4-11d7-11e6-8f4c-9b79598f5c65.jpg)
