### ISSUE TITLE
Properly handle file paths

### ISSUE THREAD

**Issue by Voltra** [mjmlio/mjml-app#343]
**Describe the bug**
Using a path that includes `&` (maybe spaces too) causes the app to not be able to open files and leaves a blank editor.

**To Reproduce**
1. Create a project with a path like `D:\pro\R&D` as the containing folder (any project name will work)
2. Choose any template
3. The editor will be empty and shows ENOENT errors in the console (e.g. `no such file or directory, scandir D:\pro\R`)

**Expected behavior**
Expects to open up just like any path that doesn't contain `&`.

**Screenshots**
![Unexpected behavior](https://image.prntscr.com/image/yy_DB5OBRJC_29S8Jhe2yg.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - App Version: v3.0.3

**Additional context**

**Comment by iRyusa** [comment]
Most likely need to escape those special chars in directory.

**Comment by Dovakiin0** [comment]
can i have a look at this?

**Comment by iRyusa** [comment]
Sure 👍

**Comment by Dovakiin0** [comment]
@iRyusa can i get a better view on the files that currently have that issue?

**Comment by staticshreyas** [comment]
I am resolving this bug! Stay tuned!
