### ISSUE TITLE
Custom MJML engine causes no render

### ISSUE THREAD

**Issue by Qu4k3** [mjmlio/mjml-app#357]
Since MJML v4.9.0 introduces big updates that are necessary, when modifying the MJML engine that brings the app to version 4.9.3, the application recognizes it, but is unable to compile or preview the result. Nor to send test mail.

![image](https://user-images.githubusercontent.com/9118664/124878247-30347a00-dfcc-11eb-84ee-1e67d58525d8.png)

Causes a no render, no errors in console.

![image](https://user-images.githubusercontent.com/9118664/124878366-50643900-dfcc-11eb-9b8d-7b405e755f55.png)

- - - - - - - - - - -

Windows 10 x64
MJML App v3.0.3
MJML v^4.8.1

MJML installed v4.9.3

**Comment by kmcb777** [comment]
Hi @Qu4k3 , it should work, but i'm not sure if you selected the right file
How did you install mjml exactly ?
When you install it somewhere with `npm install mjml`, then the file you need to select is `install_directory/node_modules/.bin/mjml`
It works for me on win10 and OSX
I'll close this for now but feel free to ask if you need further help
