### ISSUE TITLE
Template deletion without confirmation

### ISSUE THREAD

**Issue by Globaalne** [mjmlio/mjml-app#36]
Hi,

I have several times accidentally removed some ready and partially build templates just hitting the "delete" button in "My templates" view.

![2016-05-09_1159](https://cloud.githubusercontent.com/assets/19262780/15108284/c41b806a-15dd-11e6-983b-ffab28b9da13.png)

It have no confirmation on deletion and no recovery possibility. May be it is a good idea to add so called "trash" folder too, so it is possible to recover the project?

You make a grate job guys! The app truly makes template writing much faster! :)

Regates,

Globaalne

**Comment by meriadec** [comment]
Good idea.
Will be fixed in next release.

![modal mov](https://cloud.githubusercontent.com/assets/315259/15122302/c774166e-161e-11e6-9722-7ad6d5bd64e2.gif)
