### ISSUE TITLE
Can not open MJML on Mac

### ISSUE THREAD

**Issue by Emmettdoh** [mjmlio/mjml-app#378]
Hey,

Im trying to install MJMLs app on my new mac but am having some trouble. Receiving this message when I try to open. Would I please get some help? Would be really appreciated.

Thanks,
Emmet

![Screenshot 2022-06-24 at 09 39 15](https://user-images.githubusercontent.com/108122617/175498776-a263ceb5-738d-41ee-9507-733d57710c33.png)
t

**Comment by raoulwegat** [comment]
You need to allow the app because it's not signed. First, click Cancel, then open System Preferences > Security & Privacy > General tab. Click Open Anyway, then Open.
