### ISSUE TITLE
mj-img not rendering

### ISSUE THREAD

**Issue by cbanowsky** [mjmlio/mjml-app#38]
No image appears when mj-img src="blah.png" is called.

**Comment by meriadec** [comment]
The correct tag for display an image is [`mj-image`](https://mjml.io/documentation/#mj-image), and the image src has to be hosted (can't be a reference to a local file). Can you try this?

```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>

          <mj-image width="300" src="http://i.imgur.com/MTiOtUC.gif"></mj-image>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

It's working on the [live preview](https://mjml.io/try-it-live/97715849e13078f03a785ed85cbe93fc).

**Comment by fpcreator2000** [comment]
Meriadec is correct but the app still allows for you to use standard html <img> tag with it's standard attributes. I would recommend using the <mj-image> unless you images floated with text.

**Comment by meriadec** [comment]
closing this. feel free to re-open it if it wasn't enough clear.

**Comment by fillipvt** [comment]
FYI The getting started page refers to a local file https://mjml.io/getting-started/3

Got confused at first
