### ISSUE TITLE
<mj-container> tag not automatically added when new project is created.

### ISSUE THREAD

**Issue by fpcreator2000** [mjmlio/mjml-app#41]
It seems that when a new file is created the <mj-container> tag is not added to the basic new file set of tags.

**Comment by meriadec** [comment]
Good catch! Thanks

**Comment by fpcreator2000** [comment]
No a problem. Love the app as it has made me trying to guess fixes for fluid design a breeze although Outlook is still the vain of my existence. 

Thanks again guys and keep up the good work.
