### ISSUE TITLE
"New version available" message always appearing.

### ISSUE THREAD

**Issue by rojasmi1** [mjmlio/mjml-app#45]
Hi, I just noticed that the message "A brand new version of MJML App is available!" shows up even when I just downloaded the latest version available on the website.

![mjmlnew versionavailable](https://cloud.githubusercontent.com/assets/17906682/15435172/f2f659f8-1e77-11e6-9372-9b10ab3c0dd4.PNG)

**Comment by meriadec** [comment]
Hi, thanks, this has already been fixed (see #42), but binaries has not yet been re-generated as it's not very critical :)

You can use the dev version if you want the latest features!

**Comment by rojasmi1** [comment]
Thanks for the quick reply @meriadec, I will build the dev version then!

**Comment by meriadec** [comment]
You're welcome. `npm run package` to build your dedicated release :)
