### ISSUE TITLE
Wrong version info

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml-app#46]
Just tested the win version of 1.3.2 (not sure if platform specific),

The alert comes up that a new version is available,
this is shown in the about screen:

v1.3.1
mjml v2.1.1

**Comment by meriadec** [comment]
Thanks!

The modal get the version from the `package.json` file, but it apparently [has not been updated correctly when tagging v1.3.2](https://github.com/mjmlio/mjml-app/blob/master/package.json#L4). This will be corrected soon.

**Comment by janus-reith** [comment]
Well, does this happen at the time of compilation? If yes then this will solve it.

Because I also already found out about the wrong version in paackage.json (in the precompiled windows build) and changed it. While this made the version update alert disappear, the modal still shows 1.3.1.

I thought there must be another version string somewhere, else I would've sent a PR already :)

**Comment by meriadec** [comment]
Absolutely, the `package.json` is bundled (with webpack) in the minified app script. So, the `version` string too.

I dunno where it is located in Windows build, but you should find it easily (search for a `dist/bundle.js` file, then search for the string `1.3.1`) 

😃
