### ISSUE TITLE
Updates are not always saved

### ISSUE THREAD

**Issue by Akasam** [mjmlio/mjml-app#47]
Step to reproduce:
1- open the app
2- open a preexisting email
3- do some modifications
4- go back to main menu and wait for thumbnail generation 
5- quit the app
6- re-open the app
7- re-open the email

As you can see in the following screen capture, I tried to delete an empty line but this bug is reproducible for any content like fixing text or links for example.
![bug-mjml](https://cloud.githubusercontent.com/assets/1090525/15869533/1f5514c0-2ced-11e6-99ff-54d9512dfaeb.gif)

**Comment by meriadec** [comment]
Hey, thanks for reporting this, I just reproduced the bug, even in dev version, so I'm currently investigating..

Hope u didn't lost too important things!

**Comment by Akasam** [comment]
Nothing important but it is a bit annoying sometimes :)
You have to edit the email 4 or 5 times sometimes to get it saved

**Comment by Akasam** [comment]
Thanks for the quick answer !

**Comment by robsonsobral** [comment]
Even worst. I got an email "partially" saved.

I cut one `<mj-section>` and pasted before other one. The template was saved after the c... WOW! An update already! Let's try it!

**Comment by meriadec** [comment]
Should be good now.
Until we re-generate the releases, you can [build your own](https://github.com/mjmlio/mjml-app#build-from-source) :smiley:

**Comment by robsonsobral** [comment]
I just did! It looks fine on ubuntu! Thanks, @meriadec !

**Comment by Akasam** [comment]
Works fine too :)
Thanks !
