### ISSUE TITLE
Synchronize scroll

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml-app#48]
This is a really helpful feature of the try-it-live web editor and I really miss it in the app.

Is the source of the web editor available somewhere? - Would save us some time.

**Comment by meriadec** [comment]
Hi @janus-reith, this is a very good idea they had in the try-it-live. So, it's now a thing in mjml-app! You can toggle this settings in the editor settings modal:

![capture](https://cloud.githubusercontent.com/assets/315259/16005002/2f8ae564-3165-11e6-8f29-79e8ec587468.png)

Next release will include this feature, you can build your own if u can't wait :smile:

**Comment by meriadec** [comment]
Oo just realized that we should use scroll percentage instead of real scroll value to sync scrolls, because it's buggy in mobile view (can't scroll to bottom). I reopen this issue so :D

**Comment by janus-reith** [comment]
Awesome, I' ll build and try right away :D

**Comment by janus-reith** [comment]
I just tried it, for me the scroll behaviour is wrong both in desktop and mobile preview.
e.g. if i scroll to the third section in the code, the preview scrolled so far that the first 3 sections are hidden already.


The newsletter i used for testing has 402 lines of mjml code, and the desktop view newsletter length is ~3,5 the height of the preview window on a 1920x1200 24" screen.(Newsletter is displayed ~3800px long on the 1200px screen. )

**Comment by GuillaumeBadi** [comment]
This should work with the last release! 👍

**Comment by meriadec** [comment]
Nicely done, dude
