### ISSUE TITLE
Reduce font-size

### ISSUE THREAD

**Issue by crazyapple24** [mjmlio/mjml-app#49]
Please give the opportunity to reduce the font size. It's too big! Thanks

**Comment by GuillaumeBadi** [comment]
I just pushed a fix that would allow you to set the font-size you want:
9e0574bf8e7c8098c2bf7ca0df64a10b9a1aedc1

It will be on the next release!
Thanks for reporting!

**Comment by GuillaumeBadi** [comment]
![screen shot 2016-06-14 at 11 24 57](https://cloud.githubusercontent.com/assets/6558790/16037875/c3abc516-3222-11e6-8559-d4cc3f55e71b.png)

**Comment by crazyapple24** [comment]
Awesome! Thank you :)
