### ISSUE TITLE
I would like to provide windows and Linux builds for latest/upcoming releases

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml-app#50]
As there are no automated builds (possible) here atm,
I would offer to provide the builds for Windows and Linux.

**Comment by meriadec** [comment]
Hey dude!
That's awesome, it will be very appreciated 🎉 😸 😃 
We add you as collab right now.

Thanks

**Comment by GuillaumeBadi** [comment]
Hey @janus-reith !

The last version is out with cool features ! 🎉
I think you should be able to add the binaries directly to the release page: https://github.com/mjmlio/mjml-app/releases/tag/1.4.0
