### ISSUE TITLE
Duplicate template

### ISSUE THREAD

**Issue by robsonsobral** [mjmlio/mjml-app#52]
Hi!

Sometimes, we have recurrent newsletters to send. Is it possible to allow us to duplicate a template?

Maybe we could duplicate it to a folder. Something like:

- My templates folder;
- CLIENT_A newsletters;
- CLIENT_B newsletters;
- etc, etc...

I don't know what you're planning. So, I think that just to ad an option to duplicate is enough for now.

Thank you!

**Comment by meriadec** [comment]
Hi Robson,
It is a good idea. I will split it in two features:

  1. ability to duplicate a template, just basically copy it with the same name plus "-copy", or something. This can be made pretty quickly.
  2. ability to create folders, and to put templates in it, via drag & drop. We should also be able to create a folder into a folder, and so on. This is a bigger refactor of our current codebase (the way we store files, etc.). This can be a thing, but I think it will be later.

I will create another issue for the second point, this current issue will track the resolution of the first point.

Keep updated!

**Comment by meriadec** [comment]
![yolo](https://cloud.githubusercontent.com/assets/315259/16277972/62b8017c-38b5-11e6-9970-1f24e0dd2268.gif)

This ll be available in the next release. Feel free to re-build your own version!
