### ISSUE TITLE
Organize templates into folders

### ISSUE THREAD

**Issue by meriadec** [mjmlio/mjml-app#53]
As discussed in #52 , it would be cool if we can create folders, and reorder templates into them. Drag and drop is a non negociable option for that, in my opinion.

We have to discuss in the way we store the "virtual path" of each template, and how to manage folders (how to store the folder list, assign template into it, etc.). @GuillaumeBadi what do you think? A recursive explorer is a funny challenge.

**Comment by janus-reith** [comment]
As the projects are stored in separate json files,
I think the most simple way would be to not rely on real subfolders,
but simply adding a String to the json, called folder for example.

This would also maintain backwards-compatibility, as older versions would simply ignore this var in the json, and won't  remove it when saving.

**Comment by meriadec** [comment]
discussion continued in [#102](https://github.com/mjmlio/mjml-app/issues/102)
