### ISSUE TITLE
templates directory

### ISSUE THREAD

**Issue by robsonsobral** [mjmlio/mjml-app#54]
Hi! It's me again!

I guess this could create problems with the auto save, but maybe it's worth to think about.

Is it possible to allow us to open the folder where the templates are saved, so we can edit then on an advanced editor? Most of time it's just a quick addition or change. Or, even better, to set where to save the templates. We could keep them on a remote folder for more than user to access.

Thank you!

**Comment by GuillaumeBadi** [comment]
Hey !

The templates are stored in your home directory. They are not really mjml files, but json, to make auto-save quick. I think it would be a little hard, but I am going to have a deeper look at this. You still can export your templates as `.mjml` files

Guillaume

**Comment by meriadec** [comment]
well said @GuillaumeBadi, I've no more to add ^^

I'm closing this for cleaning purposes, feel free to reopen if u have some implementation ideas.
