### ISSUE TITLE
update the new file template

### ISSUE THREAD

**Issue by robsonsobral** [mjmlio/mjml-app#56]
Hi, is it possible to update the base template? It looks like outdated. Currently, it doesn't have a`<mj-head>` or `<mj-attibutes>`.

To see these features right on a new template can make new users more curious about the possibilities of MJML.

My sugestion:

```html
<mjml>
<mj-head>
  <mj-title>Hello world</mj-title>
  <mj-attributes>
    <mj-all />
    <mj-text font-size="16" />
  </mj-attributes>
</mj-head>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>

          <mj-text font-size="40">
            Hello world
          </mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by meriadec** [comment]
Yes, absolutely!
Can you provide a pull request for this? the concerned file is https://github.com/mjmlio/mjml-app/blob/master/src/assets/defaultContent.js

Thanks :)

**Comment by robsonsobral** [comment]
I can, of course (but only after you update the version of MJML). ;-)
