### ISSUE TITLE
border-radius visualization

### ISSUE THREAD

**Issue by schoolhead** [mjmlio/mjml-app#57]
It seems there is a little problem with the border-radius attribute for the button component.
Here is the MJML code I have : 
`<mj-button font-family="Raleway, Arial" font-size="16" background-color="red" border="2px solid #000" color="#fff" border-radius="11px">`
`Test button`
`</mj-button>`

And here is the result I get. First in the MJML app (on Windows 10) and then on the online MJML editor : 

![mjml-app](https://cloud.githubusercontent.com/assets/18420647/16943317/5f5d1954-4d9b-11e6-8039-a08f25179918.jpg)

![mjml-online-editor](https://cloud.githubusercontent.com/assets/18420647/16943285/3fa0e672-4d9b-11e6-8d58-70cf23ceead1.jpg)

I tried to export in html and test it on codepen. I got the same result as the app. 

`<table cellpadding="0" cellspacing="0" style="border:2px solid #000;border-radius:11px;" align="center" border="0">`
`<tbody>`
`<tr>`
`<td style="background:red;border-radius:11px;color:#fff;cursor:auto;" align="center" valign="middle" bgcolor="red">`
`<a href="" style="display:inline-block;text-decoration:none;background:red;border:1px solid red;border-radius:11px;color:#fff;font-family:Raleway, Arial;font-size:16px;font-weight:normal;padding:10px 25px;" target="_blank">Test button</a>`
`</td>`
`</tr>`
`</tbody>`
`</table>`

If you move the "border:2px solid #000;" from `<table>` to `<a>`, you get the right visualization in codepen with the border radius on the background and on the border.

In the end, it displays right on Mailjet preview and on Gmail.

**Comment by meriadec** [comment]
Interesting, thx for reporting. Maybe it is because mjml-app use the 2.2.0 version of mjml, while the current version in mjml repo is 2.3.0. I will investigate.

**Comment by meriadec** [comment]
Hi, updating to mjml 2.3.0 fixed the problem.

![oie_zw6ritrc7esy](https://cloud.githubusercontent.com/assets/315259/17037529/af9af290-4f91-11e6-85ba-3f0fa17efadc.png)
