### ISSUE TITLE
Persistent Ubuntu on clean template — OSx App

### ISSUE THREAD

**Issue by przemektrepka** [mjmlio/mjml-app#58]
When I start a new template on Mac (a clean template) I get "hello world" written in Ubuntu. As it turned out, even if I add to following attributes...
```
//mjml

<mj-head>
  <mj-attributes>
    <mj-all font-family="Montserrat" />
  </mj-attributes>
</mj-head>
```
... Ubuntu and Google Fonts @import stay regardless. My attributes on the other hand are being completely ignored.
```
// html

<head>
<style type="text/css">
  #outlook a { padding: 0; }
  .ReadMsgBody { width: 100%; }
  .ExternalClass { width: 100%; }
  .ExternalClass * { line-height:100%; }
  body { margin: 0; padding: 0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
  table, td { border-collapse:collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
  img { border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }
  p { display: block; margin: 13px 0; }
</style>
<!--[if !mso]><!-->
<style type="text/css">

  @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);

</style>
<style type="text/css">
  @media only screen and (max-width:480px) {
    @-ms-viewport { width:320px; }
    @viewport { width:320px; }
  }
</style>
<link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700" rel="stylesheet" type="text/css">
<!--<![endif]-->
<!--[if mso]>
<xml>
  <o:OfficeDocumentSettings>
    <o:AllowPNG/>
    <o:PixelsPerInch>96</o:PixelsPerInch>
  </o:OfficeDocumentSettings>
</xml>
<![endif]-->
<style type="text/css">
  @media only screen and (min-width:480px) {
    .mj-column-per-100, * [aria-labelledby="mj-column-per-100"] { width:100%!important; }
  }
</style>
<style type="text/css">
  @media only screen and (max-width:480px) {
    .mj-hero-content {
      width: 100% !important;
    }
  }
</style></head>
```

I don't get this problem in the web version.

**Comment by meriadec** [comment]
Hi, sorry for the delay. Can you give me your mjml & mjml-app versions? (click the little `?` in the app)

**Comment by przemektrepka** [comment]
pls find attached
Przemek Trepka
hi@przemektrepka.pl <mailto:hi@przemektrepka.pl>
+48606208491

**Comment by meriadec** [comment]
Hi. I didn't reproduced your problem in the dev version, neither prod version.
I just re-uploaded the mac-osx releases ensuring mjml-version is fresh. Can you try again with that? https://github.com/mjmlio/mjml-app/releases/tag/1.4.0

**Comment by meriadec** [comment]
Feel free to re-open if the problem persist :)

**Comment by webuxr** [comment]
Hello,
First time caller, long-time listener...
I need to re-open this ticket. I'm using a fresh install of mjml, set me own webfonts to use, yet I still see the Ubuntu font being output in my final HTML.

Here's my local stack:
- Mac OS Catalina v10.15.7
- Chrome v92.0.4515.15
- Node: v14.17.5
- NPM: v7.20.6
- mjml-core: 4.10.2
- mjml-cli: 4.10.2

I have the following code in my `basic.mjml` file:

```
<mjml lang="en">
  <mj-head>
    <mj-title>Foo</mj-title>
    <mj-preview>Foo</mj-preview>
    <mj-font name="roboto" 
             href="https://fonts.googleapis.com/css?family=Roboto" />
    <mj-attributes>
      <mj-all font-family="roboto, arial, sans-serif" />
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-text>Hello world!</mj-text>
  </mj-body>
</mjml>
```

...and after running the command:  
```
mjml -l strict -w basic.mjml -o ./output
```
...I get the following in the resulting HTML output:
```
<head>
   ...
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700"
        rel="stylesheet"
        type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700"
        rel="stylesheet"
        type="text/css"><!-- <= NOT COOL -->
  <link href="https://fonts.googleapis.com/css?family=Roboto"
        rel="stylesheet"
        type="text/css">
  <style type="text/css">
    @import url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700);
    @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700); /* <= NOT COOL */
    @import url(https://fonts.googleapis.com/css?family=Roboto);
  </style>
  ...
</head>
<body>
  ...
  <div style="font-family:roboto, arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;">Hello world!</div>
  ...
</body>
```

Note: I also have the mjml app installed and see the same results regardless of running 

My only caveat from the origin Op is that my "Hello world!" text is styled in Roboto. While this is what I intended, I don't want the extra HTTP request for Ubuntu. How do I prevent mjml from using Ubuntu in my final HTML (besides manually deleting the `<link>` and `@import` lines for Ubuntu)?

In addition, and perhaps an issue for a separate ticket, what's up with the double references to Roboto?

Thanks,
_rs

**Comment by webuxr** [comment]
Sorry guys... I should have done more reading. Just saw the (more applicable) posts speaking to this issue:

https://github.com/mjmlio/mjml/issues/257 and https://github.com/mjmlio/mjml/issues/216

I'll re-post my issue/questions/experience there.

Cheers,
_rs
