### ISSUE TITLE
favicon on app website

### ISSUE THREAD

**Issue by simongareste** [mjmlio/mjml-app#62]
Hi,
http://mjmlio.github.io/mjml-app/ does not have a favicon

Adding
```﻿﻿<link rel="shortcut icon" type="image/x-icon" href="https://mjml.io/favicon.ico?">```
in the headers would solve the issue I presume.

**Comment by meriadec** [comment]
Good catch. Feel free to open a PR.

**Comment by meriadec** [comment]
ps: site is on the https://github.com/mjmlio/mjml-app/tree/site branch.

**Comment by SharkChips** [comment]
I'm on it @meriadec

**Comment by meriadec** [comment]
Thanks @SharkChips !
