### ISSUE TITLE
Using "$1" or "$2" anywhere in markup breaks preview

### ISSUE THREAD

**Issue by bootsified** [mjmlio/mjml-app#64]
When I write `$1` or `$2` anywhere in the markup of the email, it breaks the preview and does very odd things.  Which sucks, especially if you're trying to build an email featuring a lot of prices. 😉  I don't know if it actually breaks the rendered HTML.

![see screenshot](https://cloud.githubusercontent.com/assets/1693606/20551921/25d2ebcc-b10b-11e6-89b9-607b5555d6f8.png)

**Comment by meriadec** [comment]
Hi, thx for the report, I will dig a bit into it.

**Comment by meriadec** [comment]
mjml-app just call mjml under the hoods to render the result. So looks like more a mjml problem.
this issue seems to report the same problem: https://github.com/mjmlio/mjml/issues/449

**Comment by bootsified** [comment]
Ah...  Makes sense.  Thanks for the help!  👍
