### ISSUE TITLE
Support for mj-include

### ISSUE THREAD

**Issue by Ndrou** [mjmlio/mjml-app#65]
Hi !

A support for mj-include would be appreciated.

When you try to open a template that contains a mj-include tag, the app display an error message : `Bad input file` 

Have a good day !

**Comment by meriadec** [comment]
Hi, @Ndrou ,
Supporting `mj-include` would be a good feature.
I will make some attempts this w-e. Keep updated.

**Comment by ibnbay99** [comment]
how about master page or template page, it would be nice :)

**Comment by meriadec** [comment]
This feature will not come soon, as it change a lot the way template are handled in the app (storing them in mjml instead of JSON actually). I can advise you to use https://atom.io/packages/mjml-preview.

**Comment by ibnbay99** [comment]
any support plugins for pycharm or on Jetbrain App :)
Thanks...
