### ISSUE TITLE
MJML strips out MailChimp's mc: attributes

### ISSUE THREAD

**Issue by impressivewebs** [mjmlio/mjml-app#67]
Hey, folks, great app, I'm really enjoying using it for my newsletter redesign.

I use MailChimp to send email, and I'm creating my new design's template using MJML app, then I export the HTML and use that to create my MailChimp template.

The following page shows MailChimp's template language:

http://templates.mailchimp.com/getting-started/template-language/

When I add those attributes to elements in my MJML template, MJML app removes them from the exported HTML.

To give you an example, I'm doing something like this throughout my MJML template:

    <mj-section mc:edit="header">

But when I export to HTML, the "mc:edit" attributes are gone.

As it stands right now, if I add these attributes in MailChimp manually, then if I have to go back and edit something in MJML app, I have to then add all the attributes again, which is tedious.

I realize this might be a difficult thing to do, because of the way the app parses and interprets the MJML tags, but would it be possible for future versions to play nice with attributes it doesn't recognize, like these ones?

Thanks!

**Comment by ngarnier** [comment]
Hey @impressivewebs, thanks for the feedback and the clear issue.

Sorry for the trouble, it's a known issue of MJML, tracked here: https://github.com/mjmlio/mjml/issues/200. I'll close this one to keep the discussion in one place but feel free to weigh in the other issue thread.

Right now, the main challenge to solve this is that one MJML component doesn't equal a single HTML element. Therefore, even if we find a way to do so, it's tricky to know on which HTML element print the custom MJML attribute.

**Comment by impressivewebs** [comment]
Ah ok, thanks. Sorry for creating a new issue, I didn't realize that would be tracked on the other repo. Thank you!

**Comment by ngarnier** [comment]
No worries :-)
