### ISSUE TITLE
Opening double curly braces crash the app

### ISSUE THREAD

**Issue by jbleuzen** [mjmlio/mjml-app#68]
App version : v1.6.0
MJML version : v3.1.1

How to reproduce : 
 1 - Open an empty template
 2 - Go anychere in code then type "{{" 
 3 - The apps hangs and finally beachball of death

What is funny, is that it's not happening on the browser demo app.

**Comment by meriadec** [comment]
hi @jbleuzen , thanks for reporting, I will investigate.

**Comment by meriadec** [comment]
it appear to be related to mjml. can you try inside a `mj-raw` ?

**Comment by jbleuzen** [comment]
Same thing…

**Comment by meriadec** [comment]
As proposed by @lohek , until a real solution exists, you can use `&#123;` instead of `{` in your template.

**Comment by jbleuzen** [comment]
Sorry for long response... 
We gave up on using mjml-app and use the cli...

**Comment by meriadec** [comment]
Np! Hope you find a workflow that feet you needs :)
