### ISSUE TITLE
Mac App - export won't remember last folder

### ISSUE THREAD

**Issue by soukupl** [mjmlio/mjml-app#69]
Hi,
it's small, but annoying problem. With each export, the file dialog will open on the root of main drive. It would be great, if the file dialog can open the last used location. This will reduce number of clicks when exporting multiple templates as mjml and html...

please :)

**Comment by meriadec** [comment]
Hi! That's a good idea. I think this can be done pretty easily.
Keep updated :)

**Comment by meriadec** [comment]
the feature is available in v1.7.0

https://github.com/mjmlio/mjml-app/releases/tag/1.7.0
