### ISSUE TITLE
Support for letter-spacing

### ISSUE THREAD

**Issue by Ifinnicus** [mjmlio/mjml-app#70]
Hey there,

It would be great if you can add a support for letter-spacing to the app.

Best regards and thanks for your great work!

**Comment by meriadec** [comment]
Hi, thanks for your support!
mjml-app directly rely on [mjml](https://github.com/mjmlio/mjml) to do the rendering part.

letter-spacing is already supported by mjml, see https://mjml.io/documentation/#mjml-text.

```xml
<mj-text letter-spacing="2px">
  lorem ipsum
</mj-text>
```

**Comment by Ifinnicus** [comment]
Sorry, I should have been more accurate! :)

I'm trying to add letter-spacing to the Text in a mj-button inside a mj-hero-content.
Is this possible?

**Comment by meriadec** [comment]
letter-spacing seems to not be supported in `mj-button` https://mjml.io/documentation/#mjml-button. Maybe you can try to use a `mj-raw` and write your custom markup in it.

Your question is more related to mjml so you may ask that in the [mjml repository](https://github.com/mjmlio/mjml).

**Comment by Ifinnicus** [comment]
Ok, I'll try it with mj-raw and if there are questions left, I will post them to the mjml repository.

Thank you!

**Comment by hansnolte** [comment]
Hi Ifinnicus,
you can try this.

```
<mj-head>
<mj-style>
.lspace {
letter-spacing: 1px;
}
</mj-style>
</mj-head>

<mj-button href="#" align="center" background-color="red" font-size="14px" border-radius="10px">
<span class="lspace">Click Me!</span></mj-button>
```
