### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml-app#71]
`npm run hot-server` / `node server.js` results in an empty page on localhost:3000 that throws and Uncaught Reference Error, stating that `module is not defined at bundle.js:1`

`npm start-hot` starts an empty Electron window with opened inspect tools, its console states: _Failed to load resource: http://localhost:3000/dist/bundle.js net::ERR_CONNECTION_REFUSED_

**Comment by meriadec** [comment]
Hi @janus-reith , I usually use `npm run dev`, that launch both `npm run hot-server` and `npm run start-hot`(this is the heritage of and old version of https://github.com/chentsulin/electron-react-boilerplate).

Do you also get the error with `npm run dev`?

**Comment by janus-reith** [comment]
Yeah I didn't bother to mention `npm run dev` because it just does these two things.
When I run it it wont open the empty electron window, but behaves the same way like I would use `npm run hot-server`. It assembles the webpack bundle and listens at localhost, page is blank and browser console throws the Uncaught Reference error.

**Comment by janus-reith** [comment]
What works is npm start, it succesfully opens the app in electron( But I won't be able to develop with that).

**Comment by meriadec** [comment]
Can you try hitting refreshing electron page (with ctrl+R / command+R depending on OS) when bundle just has finished? It can occur that the page load before bundle is available.

**Comment by janus-reith** [comment]
That did the trick!

**Comment by meriadec** [comment]
I admit this part is a bit weird. I'm currently working on refactoring this part, using the current version of electron-react-boilerplate (and the electron window now wait for bundle finish to open 😄 )

**Comment by meriadec** [comment]
Hey @janus-reith, FYI I just pushed the road-map to 2.0.0, and the -very- barebone source code for that version. Building / Launching dev env is faster and prevent the problem you described in this issue. You can check it here: https://github.com/mjmlio/mjml-app/tree/2.0.0
