### ISSUE TITLE
Refresh images in MJML app

### ISSUE THREAD

**Issue by davelantto** [mjmlio/mjml-app#72]
I'm using the MJML app on Mac, really like the app and have good success creating emails. I recently noticed an issue with images though. If I load an image or two it's fine, but if I change/update the image but keep the same file name (and URL path), it doesn't show the latest image(s) in the preview window. However if I export as HTML, the images are the latest. Is there a way to refresh the preview area to reflect image changes? Thank you!

**Comment by meriadec** [comment]
Hi @davelantto , your problem is directly related to cache created by electron to resolve already loaded images.

Maybe having a button to force clear cache in the app would be cool, I just saw https://github.com/electron/electron/blob/master/docs/api/session.md#sesclearcachecallback.

What d'you think?

**Comment by davelantto** [comment]
Thanks @meriadec, that does sound like a good idea. Would that be implemented in an upcoming release? Or is there any other way to clear the cache? Does the app have preferences that could be deleted? I'm mostly a html/css designer and I'll admit I'm pretty clueless about development programming, so please forgive my inexperience. Thank you for your help!

**Comment by meriadec** [comment]
Yes, definitely a future development. I think that clearing session HTTP cache before each render will do the trick (hope it will not slow down refresh too much => if yes, it could become an opt-in option that you could toggle un editor).

I think I can give it a try next week. Keep updated!

**Comment by janus-reith** [comment]
What works for me is to simply switch to mobile view and switch back in the right pane.
The images are relaoded then.

**Comment by janus-reith** [comment]
Maybe an efficient solution would be to check timestamps of the files every few seconds, and reload one if it changed? Probably less intensive than always reloading them .

**Comment by davelantto** [comment]
@meriadec, @janus-reith thank you both! I did try switching the mobile/desktop view but it didn't update for me...suppose it could be my system.

**Comment by davelantto** [comment]
@meriadec, @janus-reith - just wanted to let you know...the images are updating in the app now, when I overwrite them on the server. Not sure what happened, maybe there was a cache issue with my iMac, or maybe you did something. Either way, thanks!

**Comment by meriadec** [comment]
Ahah, I did nothing but I'm happy that you problem solved itself :smile:

**Comment by darylknight** [comment]
This is still an issue - images updated on server are showing the old ones in the MJML app, even after closing it

**Comment by cjl014** [comment]
This is still an issue for me. Productivity is slowed a lot just trying to figure it out or wait it out.

**Comment by Chillifish** [comment]
i just came here to find an answer to this issue, still happening now.

**Comment by georgecartridge** [comment]
> i just came here to find an answer to this issue, still happening now.

This solution worked well for me if you're still stuck:

https://github.com/mjmlio/mjml-app/issues/185#issuecomment-420025237
