### ISSUE TITLE
Why no download link for app on mjml.io

### ISSUE THREAD

**Issue by JeffCleverley** [mjmlio/mjml-app#74]
I'm new with mjml, but it's pretty awesome. 

I have been having issues with the preview package bug in Atom, so was using the online editor via mjml.io

But then I found this app, which is great. Though I look forward to being able to use preview and linter in Atom. 

I digress, I was just wondering why this App doesn't have a download link on mjml.io?

I wish I'd found it earlier.

**Comment by meriadec** [comment]
Hi Jeff, thanks for your support.

The current "politic" of mjml.io is to not promote mjml-app, in favor of MJML Atom package which also include linter, and is a bit easier to maintain (basically update the MJML version, all file system work is done by Atom).

But yeah, maybe a download link in mjml.io could be a clever way to orient new users to a fast way to use mjml, without any setup, etc. Looking forward to hear @ngarnier opinion!

**Comment by JeffCleverley** [comment]
@meriadec 

Yeah, I can appreciate that. If I could get preview to work in Atom I would be very happy indeed. 

However, since right now it isn't (neither preview nor linter), I am using a combination of the online editor for a Linter and cut and pasting to the app for preview, as I find the online editor preview to be too buggy and slow - sometimes it just doesn't update, whereas the app preview is perfect.

Either way, it's great to have mjml as a resource... even cutting and pasting to put together an Newsletter this way is still faster than creating table based templates the old way.

It's all much appreciated.

**Comment by meriadec** [comment]
Maybe you can open an issue on [the atom-mjml-preview](https://github.com/mjmlio/atom-mjml-preview) repository. It's true that it's very useful to use the same editor for all work :)

**Comment by JeffCleverley** [comment]
@meriadec I notified my problem on the already existing bug here:

https://github.com/mjmlio/atom-mjml-preview/issues/1

Cheers for your advice though.

**Comment by ngarnier** [comment]
Hey @JeffCleverley, as mentioned by @meriadec, we're rather pushing the Atom/Sublime plugins as they enable to use MJML within environments devs are often already using, and are easier for us to maintain.

However, we could totally add a link on the site, especially as Meriadec is working on a V2! What do you think about adding it on https://mjml.io/download? Or did you expect to find it somewhere else?

**Comment by JeffCleverley** [comment]
@ngarnier 

A link on the https://mjml.io/download page would be perfectly appropriate. I initially discovered mjml via your website, hence my surprise discovering the app later.

I only came across mjml on git after I swapped editors from sublime to atom. 

I look forward to @meriadec completing v.2 - keep up the great work guys.
