### ISSUE TITLE
Support emmet.io

### ISSUE THREAD

**Issue by fabianhenzler** [mjmlio/mjml-app#77]

**Comment by meriadec** [comment]
Awesome idea! Sounds like brace support emmet without too much configuration (see https://github.com/thlorenz/brace/blob/master/ext/emmet.js).

I'll be happy to merge your PR !

**Comment by fabianhenzler** [comment]
could you give me a headstart so I know how to get started? =)

**Comment by meriadec** [comment]
Sry for delay :) the feature is planned for v2. Editor is now codemirror instead of ace editor, so willl surely use https://github.com/emmetio/codemirror.

**Comment by meriadec** [comment]
Hey there, I did not achieved to integrate emmet-codemirror in our code editor. As there is not so much attraction for this feature I will close it for now.

Feel free to open a PR if you find a way!
