### ISSUE TITLE
Selected text needs better contrast ratio

### ISSUE THREAD

**Issue by jbickelhaupt** [mjmlio/mjml-app#78]
Selected text needs greater contrast when code is displayed on a dark background. It's not easy to distinguish which lines of code have been highlighted and which ones have not. See screenshot below.

![image](https://cloud.githubusercontent.com/assets/6163495/23031816/2e32d066-f427-11e6-821c-ed9c78af6459.png)

**Comment by meriadec** [comment]
Hi, you can change the editor theme in the editor settings, see for example the 'Cobalt' one:

![screen shot 2017-02-16 at 19 33 57](https://cloud.githubusercontent.com/assets/315259/23035308/ed9ab840-f47e-11e6-86cd-8c1e2a2967ae.png)

**Comment by jbickelhaupt** [comment]
Yes. I thought Clouds Midnight just seemed especially bad. Merbivore and a few others seemed kinda iffy at best. We're putting a big focus on accessibility for our website users right now, so maybe my view is just a little slanted at this point. Sorry!

**Comment by meriadec** [comment]
No pb :) maybe the default theme in mjml-app can be changed to a more accessible one.
In your opinion, which one will be the best compromise between accessibility & good integration with app design?

**Comment by jbickelhaupt** [comment]
I might go with that Cobalt suggestion you first made. I'm still a bit of a n00b at this and admittedly didn't go through EVERY theme, but I think Cobalt has some decent contrast going on—I assume we're only talking about dark themes (I had no issue with the white background on the lighter ones).

I used http://colorsafe.co/ to approximate a few colors from the app theme and see where the ratios stacked up. Obviously a few different colors to take into consideration, but I think it seemed OK.

We're borrowing heavily from 18F and making a few modifications where needed to craft our own accessibility standards. Our own color specs are listed at https://web.wsu.edu/guides/accessibility/color-and-contrast/.
