### ISSUE TITLE
<mj-wrapper> break all code

### ISSUE THREAD

**Issue by AdsonCicilioti** [mjmlio/mjml-app#79]
Se this animation:
![video_00003](https://cloud.githubusercontent.com/assets/6278398/23081239/0c8852dc-f53b-11e6-97f6-cd86bd277f9f.gif)

I'm using the app for WIndows (10), and when using the mj-wrapper the whole code is broken.

I did the test by sending an email, but it comes in the same way as the preview.

**Comment by AdsonCicilioti** [comment]
I tested it on the Atom with the preview extensions and lint, and it returns that: Error
Element mj-wrapper does not exist or is not registered.

Is there a forecast to include in the app and Atom extensions?

**Comment by ckissi** [comment]
Same happen on OSX version. Wrapper completely breaks the code. An empty screen in the preview.

**Comment by meriadec** [comment]
Hey, does your code produce the same bad result when pasting it on https://mjml.io/try-it-live ? If yes, it's rather an issue with mjml and not the app.

**Comment by ngarnier** [comment]
Hey guys, `mj-wrapper` was introduced in v3.3.0 which is currently in beta (cf https://github.com/mjmlio/mjml/releases/tag/3.3.0-beta.3), we'll update the Sublime and Atom plugins as well as the app after it's officially released (likely this week).

**Comment by ckissi** [comment]
@meriadec when I copy the same code to the online editor It works ok.

**Comment by meriadec** [comment]
fixed with https://github.com/mjmlio/mjml-app/releases/tag/1.8.0

**Comment by ckissi** [comment]
Great, waiting for 1.8.0 MacOS version :)

**Comment by meriadec** [comment]
Building it right now ^^ (then the upload on my 100 kb/s connection will take some time 😄 )

**Comment by meriadec** [comment]
Done 🎉
