### ISSUE TITLE
Aligning and padding for mj-column

### ISSUE THREAD

**Issue by puurinternet** [mjmlio/mjml-app#81]
Hello,

I've been using this tool for the first time, and while it's an interesting concept there are some things I miss (or overlooked?) For this I've used the 1.7.0 version of the win32 app.

I need to make a newsletter template that has both one and two colums (both only containing full-width images), in which the two colums align with the border of the one colum. Meaning that all the padding is in between both colums.
There are two issues that make it that I can't achieve this:

1. You can't actually align the columns
2. All columns have a default padding on them, but you can't change that or overrule it as columns have no padding attribute

Is this something I can't achieve with mjml, or am I overlooking something? See an example of how it should be below:

![design](https://cloud.githubusercontent.com/assets/12542338/23617322/0b7813fa-028d-11e7-9a0e-6d474dd5d435.jpg)
 
And an example of what I've achieved so far with mjml:

![result](https://cloud.githubusercontent.com/assets/12542338/23617614/f1b6aca0-028d-11e7-8cb8-ab3bf0e093cd.jpg)

**Comment by meriadec** [comment]
Hi @puurinternet , the mjml-app is only a wrapper around mjml.

You issue is more related to mjml, you may ask in the mjml repo: https://github.com/mjmlio/mjml :)

Happy mailing!
