### ISSUE TITLE
Failed build from source

### ISSUE THREAD

**Issue by chocopowwwa** [mjmlio/mjml-app#83]
hi, i'm trying to compile mjml-app on arch linux at branch master or tag 1.7.0
here is what happen

Command:
```
npm run dev
```

Error Message
```
ERROR in ./~/react-portal/build/portal.js
Module not found: Error: Cannot resolve module 'react/lib/CSSPropertyOperations' in /home/user/projects/mjml-app/node_modules/react-portal/build
 @ ./~/react-portal/build/portal.js 17:29-71
```

Same Issue:
tajo/react-portal#107

**Comment by meriadec** [comment]
Hi @chocopowwwa , thanks for raising. I reproduced your pb, on Arch.
I've updated react-portal to 3.0.0, and it works well now. Tells me if it's fixed on ur side!

**Comment by meriadec** [comment]
(1.7.1)
