### ISSUE TITLE
Release 1.8.0 doesn't work

### ISSUE THREAD

**Issue by Ifinnicus** [mjmlio/mjml-app#84]
Hey,

I just installed the new version of the MJML-app.
I started an old project, the preview on the right shows everything as it should be but if i try to change ANYTHING there will just pop up this message:
"Cannot read property "toString" of undefined"

Can I do something to fix this?

by the way, I'm using a Mac with OS X El Capitan 10.11.6

Thanks
Finn

**Comment by meriadec** [comment]
Hi @Ifinnicus , thx for reporting.
I didn't reproduce your problem (but I'm on Linux right now), can you paste a sample of your mjml code that you are using? It looks that the only `toString` call in mjml-app is [on the callback of mjml2html](https://github.com/mjmlio/mjml-app/blob/512352159aad3d642804d3a4c8d4e2e99b198c45/src/actions/templates.js#L101), maybe problem can be here.

**Comment by Ifinnicus** [comment]
Back in Version 1.7.0 everything's fine again by the way.

This is the beginning of my newsletter-code:

`<mjml>
  
<mj-head>
  <mj-title>Newsletter</mj-title>
  <mj-style>
      .HeadlineS {
        color: #909090;
        letter-spacing: 1.2px;
        line-height: 1;
        font-weight: lighter;
        word-break: normal;
      }
      
      .HeadlineL {
        color: #909090;
        letter-spacing: 1.2px;
        line-height: 1.2;
        font-weight: lighter;
        word-break: normal;
      }
    </mj-style>
    
  <mj-attributes>
    <mj-text  font-size="17px"
              font-family="Helvetica, Arial, Sans-Serif"
              line-height="24px"
              padding-left="15"
              padding-right="15"
              letter-spacing="0.5px"/>
              
    <mj-button  background-color="#FFFFFF"
                border-radius="0"
                inner-padding="10px 12px"
                align="center"
                font-size="20"
                />

    <mj-all   padding="0"/>
  </mj-attributes>
</mj-head>

<mj-body>
  
  <mj-container width="700px">

    <mj-section padding-top="20">
      <mj-column  width="100%">
        <mj-text  font-size="12"
                  color="#909090"
                  align="center">
          Teaser-text
        </mj-text>
      </mj-column>
    </mj-section>
    

    <mj-raw>
      <div style="margin:0px auto;max-width:700px;"><table role="presentation" cellpadding="0" cellspacing="0" style="font-size:0px;width:100%;" align="center" border="0"><tbody><tr><td style="text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px;padding-bottom:10px;"><div class="read_online mj-column-per-100 outlook-group-fix" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr><td style="word-break:break-word;font-size:0px;padding:0px;padding-right:15px;padding-left:15px;" align="center"><div class="" style="cursor:auto;color:#909090;font-family:Helvetica, Arial, Sans-Serif;font-size:12px;line-height:24px;letter-spacing:0.8px;text-align:center;letter-spacing:0.5px;">Hier geht's zur <a href="http://.../index.php?a={Kundennummer}&b={Firma1}&c={AnPerson} {Vorname} {Name}&d={Direkt - eMail}&e={Strasse}, {Land}-{PLZ} {Ort}&f={Briefanrede1}" style="text-decoration: none; color: #303030">Browseransicht</a><p></p></div></td></tr></tbody></table></div></td></tr></tbody></table></div>
    </mj-raw>
    
    
    
    

    <mj-section>
      <mj-column>
        <mj-image src="http://.../img/item_01.jpg" 
                  href="http://www.exampel.com" 
                  target="_blank"
                  alt="alt-text">
        </mj-image>
      </mj-column>  
    </mj-section>
    
    
    
    

    <mj-section padding-top="20">
      
      <mj-hero  mode="fixed-height"
                height="35px"
                background-width="650px"
                background-height="35px"
                background-url="http://.../img/line.jpg"
                alt="Linie">
        <mj-hero-content  width="100%">
          <mj-button>
            <span class="HeadlineL">HEADLINE</span>
          </mj-button>

        </mj-hero-content>
      </mj-hero>
    </mj-section>
    
    
    
    

    <mj-section>
      <mj-column  width="85%">
        <mj-text  padding-top="20"
                  font-family="Helvetica, Arial, Sans-Serif">
          <em style="font-style:normal;color:#2a2a2a;" 
              class="clFFF">{Briefanrede1}</em></br>
            texttexttexttexttexttexttexttexttexttexttexttexttexttext</br></br>
            texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext
        </mj-text>
      </mj-column>
    </mj-section>
    
    <mj-section padding-top="10px">
      <mj-column  width="60%">
        <mj-image src="http://.../global_img/signature_big_white.gif"
                  alt="alt-text"
                  title="title-text">
        </mj-image>
      </mj-column>
    </mj-section>

   </mj-container>
	</mj-body>
</mjml>`

**Comment by janus-reith** [comment]
Also can't reproduce on Windows or Linux, previous projects still work as expected.
What happens if you create a new project?

**Comment by Ifinnicus** [comment]
The beginning of the code is cut off. I don't know why. 
Its just the mjml-tag, the mj-head-tag and the opening mj-style-tag

A new project works, but when I'm copying and pasting the code of the old project into the new one it won't work again. So, I guess the my code is the problem.

`
<mjml>
<mj-head>
  <mj-style>
      .HeadlineS {
        color: #909090;
        letter-spacing: 1.2px;
        line-height: 1;
        font-weight: lighter;
        word-break: normal;
      }
      
      .HeadlineL {
        color: #909090;
        letter-spacing: 1.2px;
        line-height: 1.2;
        font-weight: lighter;
        word-break: normal;
      }
    </mj-style>
    
  <mj-attributes>
    <mj-text  font-size="17px"
              font-family="Helvetica, Arial, Sans-Serif"
              line-height="24px"
              padding-left="15"
              padding-right="15"
              letter-spacing="0.5px"/>
              
    <mj-button  background-color="#FFFFFF"
                border-radius="0"
                inner-padding="10px 12px"
                align="center"
                font-size="20"
                />

    <mj-all   padding="0"/>
  </mj-attributes>
</mj-head>

<mj-body>
  
  <mj-container width="700px">

    <mj-section padding-top="20">
      <mj-column  width="100%">
        <mj-text  font-size="12"
                  color="#909090"
                  align="center">
          Teaser-text
        </mj-text>
      </mj-column>
    </mj-section>
    

    <mj-raw>
      <div style="margin:0px auto;max-width:700px;"><table role="presentation" cellpadding="0" cellspacing="0" style="font-size:0px;width:100%;" align="center" border="0"><tbody><tr><td style="text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px;padding-bottom:10px;"><div class="read_online mj-column-per-100 outlook-group-fix" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr><td style="word-break:break-word;font-size:0px;padding:0px;padding-right:15px;padding-left:15px;" align="center"><div class="" style="cursor:auto;color:#909090;font-family:Helvetica, Arial, Sans-Serif;font-size:12px;line-height:24px;letter-spacing:0.8px;text-align:center;letter-spacing:0.5px;">Hier geht's zur <a href="http://.../index.php?a={Kundennummer}&b={Firma1}&c={AnPerson} {Vorname} {Name}&d={Direkt - eMail}&e={Strasse}, {Land}-{PLZ} {Ort}&f={Briefanrede1}" style="text-decoration: none; color: #303030">Browseransicht</a><p></p></div></td></tr></tbody></table></div></td></tr></tbody></table></div>
    </mj-raw>
    
    
    
    

    <mj-section>
      <mj-column>
        <mj-image src="http://.../img/item_01.jpg" 
                  href="http://www.exampel.com" 
                  target="_blank"
                  alt="alt-text">
        </mj-image>
      </mj-column>  
    </mj-section>
    
    
    
    

    <mj-section padding-top="20">
      
      <mj-hero  mode="fixed-height"
                height="35px"
                background-width="650px"
                background-height="35px"
                background-url="http://.../img/line.jpg"
                alt="Linie">
        <mj-hero-content  width="100%">
          <mj-button>
            <span class="HeadlineL">HEADLINE</span>
          </mj-button>

        </mj-hero-content>
      </mj-hero>
    </mj-section>
    
    
    
    

    <mj-section>
      <mj-column  width="85%">
        <mj-text  padding-top="20"
                  font-family="Helvetica, Arial, Sans-Serif">
          <em style="font-style:normal;color:#2a2a2a;" 
              class="clFFF">{Briefanrede1}</em></br>
            texttexttexttexttexttexttexttexttexttexttexttexttexttext</br></br>
            texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext
        </mj-text>
      </mj-column>
    </mj-section>
    
    <mj-section padding-top="10px">
      <mj-column  width="60%">
        <mj-image src="http://.../global_img/signature_big_white.gif"
                  alt="alt-text"
                  title="title-text">
        </mj-image>
      </mj-column>
    </mj-section>

   </mj-container>
	</mj-body>
</mjml>`

**Comment by meriadec** [comment]
After a bit digging, the issue come from mjml.
In your `mj-raw`, you have a div that has the CSS class `mj-column-per-100`, that is apparently parsed as `mj-column` by mjml, which cause a throw because it doesn't have required attributes...

So for a quick fix I will advise you to change that class name to prevent the problem.

**Comment by Ifinnicus** [comment]
Sorry for the delay! 
And thank you very much! The problem seems to be solved!
