### ISSUE TITLE
Test email dont work

### ISSUE THREAD

**Issue by ckissi** [mjmlio/mjml-app#85]
Hi,

I've tried to send a test email with mailjet credentials but it doesn't work. I've added API keys and verified sender (my mailjet login email), when I click the send button nothing happens, no message, nothing.
I've also noticed that links in the "send test email" modal don't work.

**Comment by meriadec** [comment]
Hi @ckissi , good catch, I updated the usage of node-mailjet. Fix release incoming (brace yourself).

**Comment by ckissi** [comment]
Hi @meriadec , thanks, waiting for macos package for 1.8.1

**Comment by meriadec** [comment]
should be good now @ckissi :)
