### ISSUE TITLE
Problem when referencing images with relative path

### ISSUE THREAD

**Issue by pablos91** [mjmlio/mjml-app#89]
App doesn't recognize which directory the file has been opened in.

for ex.
```
<mjml>
  <mj-body>
    <mj-container>

      <mj-section>
        <mj-column>
          <mj-image width="600" src="img/scj_HC_mailing_170320_01_01.jpg" />
        </mj-column>
      </mj-section>

    </mj-container>
  </mj-body>
</mjml>
```

renders

![image](https://cloud.githubusercontent.com/assets/1850835/24657866/3d3f1b28-1948-11e7-9056-9bd01edcc713.png)

**Comment by meriadec** [comment]
Hello @pablos91, images src must be absolute to display correctly (email recipients doesn't have access to your file system :) )
You may upload the image to an image hosting service (like http://imgur.com/) and use the url provided.

**Comment by meriadec** [comment]
see https://github.com/mjmlio/mjml-app/issues/89
