### ISSUE TITLE
Keyboard Shortcuts not working (2.0 Beta)

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#90]
Trying to copy, paste,find or cut in the code editor does not work. Code blocks can be moved around by dragging and dropping but not through regular text editing shortcuts (CMD+C, CMD+X, CMD+V, CMD+F)

**Comment by meriadec** [comment]
Thanks for reporting, I reproduced on OSX (Linux version works fine :) ).
Definitely needs to be fixed!

**Comment by dshastry** [comment]
Works in beta 2.0.0 beta2
