### ISSUE TITLE
The hardest button to button

### ISSUE THREAD

**Issue by hc-marcelino** [mjmlio/mjml-app#92]
Fairly new here so pardon the question.

How do I get the buttons within the mjml app to show up?

If I hover over an existing template, I get three bubbles with nothing in them. The icons next to "new" and "open" are missing. If I'm within a working document the arrow to back out, to the left of "export" is gone. No "i" icon in the top right corner.

oh, and images won't show up in the working file so... maybe it's a larger issue with my computer?

I'm on a Mac using v1.8.1, mjml v3.3.0

**Comment by meriadec** [comment]
Regarding the symptom you are describing, I think you are just... disconnected from the internet? 😄  I mean, all the icons of the v1.* come from [the ionicon CDN](http://ionicons.com/), and the images are not showing up probably because they refer to distant URLs. Does the problem persists?

**Comment by hc-marcelino** [comment]
I am restricted by a proxy but the ionicons.com site is accessible. Also, in regards to the images being used in the default templates, if I export to html the images show up.

**Comment by meriadec** [comment]
interesting.. can you try with the app version 2 ? https://github.com/mjmlio/mjml-app/releases

**Comment by hc-marcelino** [comment]
I like the app update! I had tried it previously but there wasn't any templates available at the time. As you may notice, I'm not a daily user.

I don't notice any missing icons, although I'm not 100% sure what it's suppose to look like. I am having the same issues though. The images that are used in the templates display as missing links; alt image description inside a grey border box with a generic image icon of a green hill, blue sky with a white cloud. If I export to html, the images come up.

Not a huge deal on my end since I'm swapping those out. Just an initial nuisance, when adjusting the initial template for this novice user.

**Comment by meriadec** [comment]
Can you reproduce those steps:

1) Open the app (close->reopen if already opened)
2) Open the developer tools (View->Toggle developer tools)
3) Navigate to the "Network" tab of the developers tools
4) Open your project inside the app
5) Take a screenshot

Should look like this:
![screenshot-1493214061_1304x983](https://cloud.githubusercontent.com/assets/315259/25437541/fca0afd6-2a96-11e7-80fa-0019a243446c.png)

So I can see the error codes you have for the images.

**Comment by hc-marcelino** [comment]
I guess we found another issue.

![mjml](https://cloud.githubusercontent.com/assets/26149400/25438130/1d17111c-2a5e-11e7-8805-27780cbc4c2d.png)

**Comment by meriadec** [comment]
I honestly don't know why you got 307 status on all those images (which means [temporary redirect](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307)).

Can you try with another internet source (e.g: 4G mobile data share) ? Maybe it's because the images are served on `http` and not `https` and you have network restriction. Anyway, I can't reproduce on my side.

The glitches appearing in screenshot are not related to app (either electron-renderer, or your GPU / video chipset)

**Comment by hc-marcelino** [comment]
IT did mention something about http vs https and why I can't use firefox at all now. I'm definitely restricted to this network for security reasons. Thanks for following up.

I will research the glitches. I don't want to invade this thread on a different issue but could you point me in the right direction for that?
