### ISSUE TITLE
MJML 1.0 Projects not visible in MJML 2 Beta

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#93]
MJML 1.0 projects are not visible in 2 beta, however, the reverse is true. Screenshots attached to document issue

![image](https://cloud.githubusercontent.com/assets/4194561/24933304/5017434a-1edb-11e7-8a5a-e0819e77393e.png)

![image](https://cloud.githubusercontent.com/assets/4194561/24933313/58ebb7bc-1edb-11e7-97f7-e0df1ecd84e1.png)

**Comment by meriadec** [comment]
The v1 and v2 are not supposed to be compatible, as we do not store the templates the same way.

- For v1, we store a JSON for each template, in a `mjml-app` folder in `$HOME`. That JSON contain the MJML and HTML, as string.
- For v2, we simply use the file system, in the folder of the project given.

So... in fact I'm very surprised that you have the v2 project appear in the v1 app :thinking: . Sounds like a glitch in the matrix.

**Comment by dshastry** [comment]
I did notice the difference you mentioned, and after reading the release notes that's what I figured. But I am able to view and edit code produced between both versions.

I have a library of templates built in v1.0; will those formally be available for editing in v2?

**Comment by meriadec** [comment]
Absolutely, language is the same so your templates will be compatible, but you will have to manually import them in the v2 app.

**Comment by dshastry** [comment]
Cool. Also maybe a separate question, but is there a way we can integrate MJML into existing wysiwyg editors like TinyMCE or the Wordpress editor? We have a custom CRM in house CRM, and I'm trying to push my organization to use MJML for email. I'd like them to get off using traditional hand coding of tables since no one is really a developer/designer, but adoption is going to be challenging because I'm asking them to learn another tool. Any way we can easily integrate into existing tools people are familiar with?

**Comment by dshastry** [comment]
And to add some additional insight we already have a mail infrastructure in place so integrating with Mailjet via API was out of the question unfortunately. Trying to see if there's a plugin or extension that we can integrate with to essentially parse and display our MJML code in HTML.

**Comment by meriadec** [comment]
I think the easiest way to integrate MJML in your workflow is to use the MJML API https://mjml.io/api. A simple call, you get your HTML, and go!

**Comment by meriadec** [comment]
If you have specific needs like that, you may join the MJML slack https://mjml.slack.com/, guys are very reactive and you will surely find more precise answers.

**Comment by dshastry** [comment]
Awesome! I'll do that now. Thanks @meriadec
