### ISSUE TITLE
Mobile Preview missing

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#94]
Previous version of MJML had a responsive toggle button to show mobile media queries. Buttons are missing on newer beta, however by sliding the width of the preview pane the same functionality can be replicated.

Screenshots attached to document:

![image](https://cloud.githubusercontent.com/assets/4194561/24933431/e6ee7d9c-1edb-11e7-91f9-71e5b5455b56.png)

![image](https://cloud.githubusercontent.com/assets/4194561/24933455/02853f64-1edc-11e7-941c-01a90b98c527.png)

**Comment by meriadec** [comment]
Hey @dshastry , yes, initially that was intended, as like you said, user can slide the bar to adjust size the way he want.

But if you think it's missing, you may not be the only one, so I think we can put back this feature, that will just force size to hard coded values (like 300px for mobile / 600px for desktop).

I think I will put an "actions overlay" on the preview, that will show on hover, and will allow to resize to mobile/desktop + show the result HTML.

**Comment by meriadec** [comment]
Thanks for the feedbacks :)

**Comment by dshastry** [comment]
That sounds like a great UX solve for it @meriadec! Perhaps even pushing it one step further, you can allow users to define the two breakpoints they want in a settings interface somewhere, and then have those two values available as buttons on hover. Then they can toggle between custom desktop/mobile widths.

**Comment by meriadec** [comment]
Hey there. Now you are able to toggle between mobile/destkop *AND* to define the sizes of the desktop / mobile in the settings modal.

The switcher appears only on hover, so it will not pollute the preview.

Keep updated for the release!

![screenshot-1492165761_634x336](https://cloud.githubusercontent.com/assets/315259/25041129/17cf674e-210e-11e7-8230-7bf24adb56a3.png)
![toto](https://cloud.githubusercontent.com/assets/315259/25041130/17d06d10-210e-11e7-914b-a67431ad9b42.png)

**Comment by meriadec** [comment]
(and as a bonus: the last used preview size is restored when changing templates / restarting app)
