### ISSUE TITLE
Search Feature Missing - Beta 2.0.0-beta 3 

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#99]
The code search option is missing in the latest beta release. CMD+F does not pull up search box either.

Search box from previous release attached below for reference:

![image](https://cloud.githubusercontent.com/assets/4194561/25094014/baafd338-235a-11e7-9593-bbf573f117b6.png)

**Comment by meriadec** [comment]
Added codemirror search feature.

![search](https://cloud.githubusercontent.com/assets/315259/25278771/be8e04fa-26a4-11e7-8f18-24ae466a0887.gif)

I will close the issue on 2.0.0 release.

**Comment by dshastry** [comment]
awesome!!
